FROM registry.opensuse.org/opensuse/bci/bci-init:latest

RUN zypper in -y \
        podman \
        git \
        golang \
        gawk \
    && zypper clean all

# Force podman/buildah onto fuse-overlayfs instead of native kernel overlay,
# to avoid nested overlay-on-overlay failures
# This gets around https://github.com/podman-container-tools/buildah/issues/6892
RUN mkdir -p /etc/containers && \
    cat <<'EOF' > /etc/containers/storage.conf
[storage]
driver = "overlay"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
EOF

# remove some units that end up always crashing
RUN systemctl mask \
        systemd-remount-fs.service \
        dev-hugepages.mount \
        sys-fs-fuse-connections.mount \
        systemd-logind.service \
        getty.target \
        console-getty.service

RUN mkdir -p /etc/containers/systemd \
 && mkdir -p /var/lib/materia/components \
 && mkdir -p /usr/local/bin

# Install dbus policy file
COPY install/systems.primamateria.materia.conf /etc/dbus-1/system.d/systems.primamateria.materia.conf

# module cache
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

RUN systemctl enable podman.socket

RUN git config --global user.name "Materia User"
RUN git config --global user.email "notreal@primamateria.systems"


STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
