[tools]
fnox = "latest"

[vars]
image_registry = "${IMAGE_REGISTRY:-}"
gh_mirror = "stryan/materia"

[tasks.ci-build]
description = "Build and test for CI"
depends = ["build", "test", "integration -k"]

[tasks.ci-image]
description = "Build CI image"
usage = '''
  arg "[tag]" help = "Tag to push, omit to build only without pushing"
'''
run = '''
  if [ -n "$usage_tag" ]; then
    docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 --push -t {{vars.image_registry}}/materia:"$usage_tag" -t ghcr.io/stryan/materia:"$usage_tag" .
  else
    docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 .
  fi
'''

[tasks.ci-release]
description = "Build images for release"
tools.gh = "latest"
usage = '''
  arg "<tag>" help = "Tag to push"
  arg "[repos]" help = "Repositorys to push to" var=#true
'''
run = [
  "git remote add mirror git@github.com:stryan/materia", #need this for gh
  "mise run ci-buildah --stable ${usage_tag?} {{vars.image_registry}} {{vars.gh_mirror}}",
  "fnox x -- gh release create ${usage_tag?} -d -F CHANGELOG.md --generate-notes ./bin/materia*",
  "git remote rm mirror",
]

[tasks.ci-buildah]
depends = ["build-amd64", "build-arm64"]
usage = '''
  arg "[tag]" help = "Tag to push, omit to build only without pushing"
  arg "[repos]" help = "Repositorys to push to" var=#true
  flag "-s --stable" help="Make this release a stable release" default=#false
  flag "-t --test" negate="--no-test" help="Test if the image can be run with buildah run" default=#true
  flag "-c --clear" negate="--no-clear" help="Clear buildah cache of previous materia manifests" default=#true
'''
run = '''
  if [[ "${usage_clear}" == "true" ]]; then
    buildah manifest rm materia 2>/dev/null || true # clear old manifest from buildah cache
  fi
  buildah build --platform linux/arm64,linux/amd64 --manifest materia -f Containerfile.ci .
  if [[ "${usage_test}" == "true" ]]; then
    host_arch="$(go env GOARCH)"
    ctr="$(buildah from --pull=never --arch "$host_arch" localhost/materia:latest)" # grab the image for the runner arch from the manifest
    trap 'buildah rm "$ctr" >/dev/null 2>&1 || true' EXIT # trap to catch mise's term signal and remove the above image on failure
    buildah run "$ctr" -- /app/materia version
    buildah run "$ctr" -- /app/materia --help
  fi
  if [ -n "$usage_tag" ]; then
    if [ -z "${usage_repos}" ]; then
      echo "a tag was given but no repos to push to" >&2
      exit 1
    fi
    for repo in ${usage_repos}; do
      buildah manifest push --all materia docker://${repo}/materia:"$usage_tag"
      if [[ "${usage_stable}" == "true" ]]; then
        buildah manifest push --all materia docker://${repo}/materia:stable
      fi
    done
  fi
'''


# Override main mise one to use remote podman in CI
[tasks.build-test-container]
description = "Build image used for test container"
sources = ["Containerfile.test", "go.mod", "go.sum", "install/systems.primamateria.materia.conf"]
outputs = { auto = true } # maybe someday mise will support oci outputs
run = """
	podman --remote build -f Containerfile.test -t materia-testcontainer:latest .
"""

[tasks.clean-test-containers]
run = """
	podman ps -aq --filter "label=org.testcontainers=true" | xargs -r podman rm -f
"""
