[env]
DOCKER_HOST="unix:///var/run/podman/podman.sock"
CONTAINER_HOST="unix:///var/run/podman/podman.sock"
CGO_ENABLE = "0"
BUILDAH_ISOLATION="chroot"

[vars]
image_registry = "${IMAGE_REGISTRY}"
gh_repo = "stryan/materia"

[tasks.ci-build]
description = "Build and test for CI"
depends = ["build", "test", "integration -k"]

[tasks.ci-image]
description = "Build CI image"
usage = '''
  arg "[tag]" help = "Tag to push, omit to build only without pushing"
'''
run = '''
  if [ -n "$usage_tag" ]; then
    docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 --push -t {{vars.image_registry}}/materia:"$usage_tag" -t ghcr.io/stryan/materia:"$usage_tag" .
  else
    docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 .
  fi
'''

[tasks.ci-release]
description = "Build images for release"
tools.gh = "latest"
usage = '''
  arg "<tag>" help = "Tag to push"
'''
run = [
  "git remote add mirror git@github.com:stryan/materia", #need this for gh
  "mise run ci-buildah --stable ${usage_tag?}",
  "gh release create ${usage_tag?} -d -F CHANGELOG.md --generate-notes ./bin/materia*",
  "git remote rm mirror",
]

# For post-migration
[tasks.ci-buildah]
depends = ["build-amd64", "build-arm64"]
usage = '''
  arg "[tag]" help = "Tag to push, omit to build only without pushing"
  flag "-s --stable" help="Make this release a stable release" default=#false
'''
run = '''
  buildah build --platform linux/arm64,linux/amd64 --manifest materia -f Containerfile.ci .
  if [ -n "$usage_tag" ]; then
    buildah manifest push --all materia docker://{{vars.image_registry}}/materia:"$usage_tag"
    [[ "${usage_stable}" == "true" ]] && buildah manifest push --all materia docker://{{vars.image_registry}}/materia:stable
    buildah manifest push --all materia docker://ghcr.io/{{vars.gh_repo}}:"$usage_tag"
    [[ "${usage_stable}" == "true" ]] && buildah manifest push --all materia docker://ghcr.io/{{vars.gh_repo}}:stable
  fi
'''


# Override main mise one to use remote podman in CI
[tasks.build-test-container]
description = "Build image used for test container"
sources = ["Containerfile.test", "go.mod", "go.sum", "install/systems.primamateria.materia.conf"]
outputs = { auto = true } # maybe someday mise will support oci outputs
run = """
	podman --remote build -f Containerfile.test -t materia-testcontainer:latest .
"""

[tasks.clean-test-containers]
run = """
	podman ps -aq --filter "label=org.testcontainers=true" | xargs -r podman rm -f
"""
