[vars]
container_tag = "${TAG}"
image_registry = "${IMAGE_REGISTRY}"

[tasks.ci]
env = { CGO_ENABLE = 0}
depends = ["build","test"]
run = 'docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 --push -t {{vars.image_registry}}/materia:{{vars.container_tag}} .'
