[tools]
go = "1.27"
"go:golang.org/x/tools/cmd/stringer" = "latest"
"go:github.com/varlink/go/cmd/varlink-go-interface-generator" = "latest"
golangci-lint = "2.13.2"
gotestsum = "latest"
mockery = "3.7.4"
sops = "latest"

[settings]
experimental = true

[env]
DOCKER_HOST = "unix://{{get_env(name='XDG_RUNTIME_DIR',default='/var/run')}}/podman/podman.sock"

[vars]
CURRENTBRANCH = "{{exec(command='git rev-parse --abbrev-ref HEAD')}}"
PKGVERSION = '{{exec(command="git describe --tags --abbrev=8 --dirty --always --long")}}'
LDFLAGS = "{{ get_env(name='LDFLAGS',default='-w -s') }} -X 'main.Version={{vars.PKGVERSION}}'"
NOCGO = "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp"
releasedir = "./dist"
release_archs = "amd64 arm64"

[tasks.container]
depends = ["build", "lint", "test"]
env = { LDFLAGS = '-ldflags="-w -s"' }
run = "podman build -f Containerfile.ci -t primamateria.systems/materia:latest ."

[tasks.build-test-container]
description = "Build image used for test container"
sources = [
  "Containerfile.test",
  "go.mod",
  "go.sum",
  "install/systems.primamateria.materia.conf",
]
outputs = { auto = true } # maybe someday mise will support oci outputs
run = "podman build -f Containerfile.test --platform linux/amd64 -t materia-testcontainer:latest ."

[tasks.build]
depends = ["generate", "build-arm64", "build-amd64"]

[tasks.fmt]
depends = ["generate"]
sources = ["**/*.go", "go.mod", "go.sum"]
outputs = { auto = true }
run = "golangci-lint fmt ./cmd/... ./internal/... ./pkg/..."

[tasks.lint]
depends = ["generate"]
sources = ["**/*.go", "go.mod", "go.sum"]
outputs = { auto = true }
run = "golangci-lint run ./cmd/... ./internal/... ./pkg/..."

[tasks.test]
depends = ["fmt", "lint"]
usage = '''
flag "-v --verbose" help="Verbose gotestum output" default=#false
'''
run = [
  "gotestsum {% if usage.verbose %} --format standard-verbose {% endif %} -- -tags '{{ vars.NOCGO }}' ./cmd/... ./internal/... ./pkg/...",
]

[tasks.virter]
depends = ["build-amd64"]
tools."github:LINBIT/virter" = "latest"
usage = """
  flag "-f --fresh" help="Create a new VM if one is currently running" default=#false
"""
run = """
  #!/usr/bin/env bash
  [[ "${usage_fresh}" == "true" ]] && if virter vm exists materia-explore-alma-9; then virter vm rm materia-explore-alma-9; fi
  if ! virter vm exists materia-explore-alma-9; then virter vm run --name materia-explore-alma-9 --id 102 --wait-ssh alma-9; fi
  virter vm exec materia-explore-alma-9 --provision virter/virter_explore.toml
"""

[tasks.generate]
description = "Run go:generate"
sources = [
  "**/*.go",
  ".mockery.yml",
  "go.mod",
  "go.sum",
  "pkg/api/systems.primamateria.materia.varlink",
]
outputs = { auto = true }
run = [
  "go generate ./...",
  "varlink-go-interface-generator pkg/api/systems.primamateria.materia.varlink",
  "mockery",
]

[tasks.build-amd64]
depends = ["build-materia-amd64"]

[tasks.build-arm64]
depends = ["build-materia-arm64"]

[tasks.build-materia-arm64]
depends = ["lint"]
description = "Build the project for arm64"
sources = ["**/*.go", "go.mod", "go.sum"]
outputs = ["./bin/materia-arm64"]
env = { GOOS = "linux", GOARCH = "arm64", CGO_ENABLED = 0 }
run = 'go build -tags "{{vars.NOCGO}}" -ldflags="{{vars.LDFLAGS}}" -o bin/materia-arm64 ./cmd/materia/'

[tasks.build-materia-amd64]
depends = ["lint"]
description = "Build the project for amd64"
sources = ["**/*.go", "go.mod", "go.sum"]
outputs = ["./bin/materia-amd64"]
env = { GOOS = "linux", GOARCH = "amd64", CGO_ENABLED = 0 }
run = 'go build -tags "{{vars.NOCGO}}" -ldflags="{{vars.LDFLAGS}}" -o bin/materia-amd64 ./cmd/materia/'

[tasks.docs]
description = "generate manpages"
dir = "docs"
tools.pandoc = "latest"
run = [
  "rm -rf output/man && mkdir -p output/man",
  "find . -iname \"*.*.md\" -type f -exec sh -c 'pandoc \"${0}\" -f commonmark_x -s -t man -o output/man/\"$(basename ${0%.md})\"' {} \\; ",
]

[tasks.release-tar]
description = "generate release tarballs"
depends = ["build", "docs"]
usage = '''
  arg "[version]" help="Manually specify version being released"
'''
run = '''
  #!/usr/bin/env bash
  set -euo pipefail
  VERSION=${usage_version:-$(git describe --exact-match --tags --match 'v[0-9]*' HEAD 2>/dev/null || git rev-parse --abbrev-ref HEAD)}
  epoch=$(git log -1 --format=%ct HEAD)
  rm -rf {{vars.releasedir}} && mkdir -p {{vars.releasedir}}
  for arch in {{vars.release_archs}}; do
    tmpdir=$(mktemp -d)
    chmod 755 "$tmpdir"
    mkdir -p "$tmpdir"/bin "$tmpdir"/man/man1 "$tmpdir"/man/man5
    cp ./README.md "$tmpdir"/
    cp ./LICENSE "$tmpdir"/
    cp docs/output/man/*.1 "$tmpdir"/man/man1/
    cp docs/output/man/*.5 "$tmpdir"/man/man5/
    cp install/systems.primamateria.materia.conf "$tmpdir"/
    cp bin/materia-$arch "$tmpdir"/bin/materia
    tar --sort=name --mtime="@$epoch" --owner=0 --group=0 --numeric-owner \
      -cf - -C "$tmpdir" . | gzip -n > "{{vars.releasedir}}/materia-$VERSION-$arch.tar.gz"
    rm -rf "$tmpdir"
  done
  git archive --format=tar.gz -o {{vars.releasedir}}/materia-$VERSION-src.tar.gz --prefix="materia-${VERSION#v}/" $VERSION
'''

[tasks.release-sign-tar]
tools.cosign = "latest"
description = "SHA checksums and cosign the release tarballs"
dir = "{{vars.releasedir}}"
run = '''
	#!/usr/bin/env bash
	set -euo pipefail
	sha256sum $(ls | grep -v -e '^SHA256SUMS' -e '\.asc$' -e '\.bundle$') > SHA256SUMS
	cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY --bundle SHA256SUMS.cosign.bundle SHA256SUMS
'''

[tasks.release-sign-image]
tools.cosign = "latest"
description = "Cosign image from digest file"
usage = '''
  arg "<digestfile>" help="Digest file path"
  arg "<repo>" help="Repo to sign at"
'''
run = '''
	#!/usr/bin/env bash
	set -euo pipefail
	digest=$(<"${usage_digestfile?}")
	cosign sign --yes --recursive --key env://COSIGN_PRIVATE_KEY "${usage_repo?}@$digest"
	cosign verify --key cosign.pub "${usage_repo?}@$digest" >/dev/null
'''

[tasks.vulncheck]
tools = { "go:golang.org/x/vuln/cmd/govulncheck" = "latest" }
run = "govulncheck ./..."

[tasks.integration]
tools.age = "latest"
depends = ["build", "build-test-container"]
usage = '''
  arg "[test]" help="Test to run"
  flag "-k --keep" help="Keep container after running" default=#false
'''
raw = true
run = '''
  export TESTCONTAINERS_RYUK_DISABLED={{usage.keep}}
  export MATERIA_KEEP_TEST_CONTAINER={{usage.keep}}
  export MATERIA_TEST_IMAGE=materia-testcontainer:latest
  gotestsum --format standard-verbose -- \
  {%- if usage.test != "" -%} -run {{usage.test}} \ {%- endif -%}
  -v \
  -failfast \
  -count=1 \
  ./scripts/integration-tests/...
'''
