[vars]
container_tag = "${TAG}"

[tasks.ci]
env = { CGO_ENABLE = 0}
depends = ["build","test"]
run = 'docker buildx build -f Containerfile.ci --platform linux/arm64,linux/amd64 --push -t git.saintnet.tech/stryan/materia:{{vars.container_tag}} .'
