// Code generated by "stringer -type ActionType -trimprefix Action"; DO NOT EDIT.

package actions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionUnknown-0]
	_ = x[ActionInstall-1]
	_ = x[ActionRemove-2]
	_ = x[ActionUpdate-3]
	_ = x[ActionStart-4]
	_ = x[ActionStop-5]
	_ = x[ActionRestart-6]
	_ = x[ActionReload-7]
	_ = x[ActionEnable-8]
	_ = x[ActionDisable-9]
	_ = x[ActionEnsure-10]
	_ = x[ActionSetup-11]
	_ = x[ActionCleanup-12]
	_ = x[ActionMount-13]
	_ = x[ActionImport-14]
	_ = x[ActionDump-15]
	_ = x[ActionExecute-16]
}

const _ActionType_name = "UnknownInstallRemoveUpdateStartStopRestartReloadEnableDisableEnsureSetupCleanupMountImportDumpExecute"

var _ActionType_index = [...]uint8{0, 7, 14, 20, 26, 31, 35, 42, 48, 54, 61, 67, 72, 79, 84, 90, 94, 101}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
