# These secrets are only accesible to the host named "warden"
[globals]
flask = "thrown" # Any component assigned to warden has access to this secret
[components.beszel-server]
containerTag = "stable" # override the default containerTag with "stable"
