// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package systemsprimamateriamateria

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

type SyncFailed struct {
	Message string `json:"message"`
}

func (e SyncFailed) Error() string {
	s := "systems.primamateria.materia.SyncFailed"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

type PlanFailed struct {
	Message string `json:"message"`
}

func (e PlanFailed) Error() string {
	s := "systems.primamateria.materia.PlanFailed"
	s += fmt.Sprintf("(Message: %v)", e.Message)
	return s
}

type ExecutionFailed struct {
	Message        string `json:"message"`
	StepsCompleted int64  `json:"stepsCompleted"`
	TotalSteps     int64  `json:"totalSteps"`
}

func (e ExecutionFailed) Error() string {
	s := "systems.primamateria.materia.ExecutionFailed"
	s += fmt.Sprintf("(Message: %v, StepsCompleted: %v, TotalSteps: %v)", e.Message, e.StepsCompleted, e.TotalSteps)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "systems.primamateria.materia.SyncFailed":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param SyncFailed
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "systems.primamateria.materia.PlanFailed":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param PlanFailed
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "systems.primamateria.materia.ExecutionFailed":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param ExecutionFailed
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// Returns host facts. Use hostOnly to ignore facts related to role
type Facts_methods struct{}

func Facts() Facts_methods { return Facts_methods{} }

func (m Facts_methods) Call(ctx context.Context, c *varlink.Connection, hostOnly_in_ bool) (facts_out_ string, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, hostOnly_in_)
	if err_ != nil {
		return
	}
	facts_out_, _, err_ = receive(ctx)
	return
}

func (m Facts_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, hostOnly_in_ bool) (func(ctx context.Context) (string, uint64, error), error) {
	var in struct {
		HostOnly bool `json:"hostOnly"`
	}
	in.HostOnly = hostOnly_in_
	receive, err := c.Send(ctx, "systems.primamateria.materia.Facts", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (facts_out_ string, flags uint64, err error) {
		var out struct {
			Facts string `json:"facts"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		facts_out_ = out.Facts
		return
	}, nil
}

func (m Facts_methods) Upgrade(ctx context.Context, c *varlink.Connection, hostOnly_in_ bool) (func(ctx context.Context) (facts_out_ string, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		HostOnly bool `json:"hostOnly"`
	}
	in.HostOnly = hostOnly_in_
	receive, err := c.Upgrade(ctx, "systems.primamateria.materia.Facts", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (facts_out_ string, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Facts string `json:"facts"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		facts_out_ = out.Facts
		return
	}, nil
}

// Returns the current plan. empty=true means no changes pending.
type Plan_methods struct{}

func Plan() Plan_methods { return Plan_methods{} }

func (m Plan_methods) Call(ctx context.Context, c *varlink.Connection) (plan_out_ string, len_out_ int64, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	plan_out_, len_out_, _, err_ = receive(ctx)
	return
}

func (m Plan_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (string, int64, uint64, error), error) {
	receive, err := c.Send(ctx, "systems.primamateria.materia.Plan", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (plan_out_ string, len_out_ int64, flags uint64, err error) {
		var out struct {
			Plan string `json:"plan"`
			Len  int64  `json:"len"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		plan_out_ = out.Plan
		len_out_ = out.Len
		return
	}, nil
}

func (m Plan_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (plan_out_ string, len_out_ int64, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "systems.primamateria.materia.Plan", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (plan_out_ string, len_out_ int64, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Plan string `json:"plan"`
			Len  int64  `json:"len"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		plan_out_ = out.Plan
		len_out_ = out.Len
		return
	}, nil
}

// Syncs the local source repo to the latest revision.
// Pass revision to pin to a specific ref, leave empty for latest.
type Sync_methods struct{}

func Sync() Sync_methods { return Sync_methods{} }

func (m Sync_methods) Call(ctx context.Context, c *varlink.Connection, revision_in_ *string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, revision_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Sync_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, revision_in_ *string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Revision *string `json:"revision,omitempty"`
	}
	in.Revision = revision_in_
	receive, err := c.Send(ctx, "systems.primamateria.materia.Sync", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Sync_methods) Upgrade(ctx context.Context, c *varlink.Connection, revision_in_ *string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Revision *string `json:"revision,omitempty"`
	}
	in.Revision = revision_in_
	receive, err := c.Upgrade(ctx, "systems.primamateria.materia.Sync", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Plans and executes an update. Returns number of steps completed.
type Update_methods struct{}

func Update() Update_methods { return Update_methods{} }

func (m Update_methods) Call(ctx context.Context, c *varlink.Connection) (steps_out_ int64, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	steps_out_, _, err_ = receive(ctx)
	return
}

func (m Update_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (int64, uint64, error), error) {
	receive, err := c.Send(ctx, "systems.primamateria.materia.Update", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (steps_out_ int64, flags uint64, err error) {
		var out struct {
			Steps int64 `json:"steps"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		steps_out_ = out.Steps
		return
	}, nil
}

func (m Update_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (steps_out_ int64, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "systems.primamateria.materia.Update", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (steps_out_ int64, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Steps int64 `json:"steps"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		steps_out_ = out.Steps
		return
	}, nil
}

// Generated service interface with all methods

type systemsprimamateriamateriaInterface interface {
	Facts(ctx context.Context, c VarlinkCall, hostOnly_ bool) error
	Plan(ctx context.Context, c VarlinkCall) error
	Sync(ctx context.Context, c VarlinkCall, revision_ *string) error
	Update(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

func (c *VarlinkCall) ReplySyncFailed(ctx context.Context, message_ string) error {
	var out SyncFailed
	out.Message = message_
	return c.ReplyError(ctx, "systems.primamateria.materia.SyncFailed", &out)
}

func (c *VarlinkCall) ReplyPlanFailed(ctx context.Context, message_ string) error {
	var out PlanFailed
	out.Message = message_
	return c.ReplyError(ctx, "systems.primamateria.materia.PlanFailed", &out)
}

func (c *VarlinkCall) ReplyExecutionFailed(ctx context.Context, message_ string, stepsCompleted_ int64, totalSteps_ int64) error {
	var out ExecutionFailed
	out.Message = message_
	out.StepsCompleted = stepsCompleted_
	out.TotalSteps = totalSteps_
	return c.ReplyError(ctx, "systems.primamateria.materia.ExecutionFailed", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyFacts(ctx context.Context, facts_ string) error {
	var out struct {
		Facts string `json:"facts"`
	}
	out.Facts = facts_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyPlan(ctx context.Context, plan_ string, len_ int64) error {
	var out struct {
		Plan string `json:"plan"`
		Len  int64  `json:"len"`
	}
	out.Plan = plan_
	out.Len = len_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplySync(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyUpdate(ctx context.Context, steps_ int64) error {
	var out struct {
		Steps int64 `json:"steps"`
	}
	out.Steps = steps_
	return c.Reply(ctx, &out)
}

// Generated dummy implementations for all varlink methods

// Returns host facts. Use hostOnly to ignore facts related to role
func (s *VarlinkInterface) Facts(ctx context.Context, c VarlinkCall, hostOnly_ bool) error {
	return c.ReplyMethodNotImplemented(ctx, "systems.primamateria.materia.Facts")
}

// Returns the current plan. empty=true means no changes pending.
func (s *VarlinkInterface) Plan(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "systems.primamateria.materia.Plan")
}

// Syncs the local source repo to the latest revision.
// Pass revision to pin to a specific ref, leave empty for latest.
func (s *VarlinkInterface) Sync(ctx context.Context, c VarlinkCall, revision_ *string) error {
	return c.ReplyMethodNotImplemented(ctx, "systems.primamateria.materia.Sync")
}

// Plans and executes an update. Returns number of steps completed.
func (s *VarlinkInterface) Update(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "systems.primamateria.materia.Update")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "Facts":
		var in struct {
			HostOnly bool `json:"hostOnly"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.systemsprimamateriamateriaInterface.Facts(ctx, VarlinkCall{call}, in.HostOnly)

	case "Plan":
		return s.systemsprimamateriamateriaInterface.Plan(ctx, VarlinkCall{call})

	case "Sync":
		var in struct {
			Revision *string `json:"revision,omitempty"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.systemsprimamateriamateriaInterface.Sync(ctx, VarlinkCall{call}, in.Revision)

	case "Update":
		return s.systemsprimamateriamateriaInterface.Update(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `systems.primamateria.materia`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface systems.primamateria.materia

# Returns host facts. Use hostOnly to ignore facts related to role
method Facts(hostOnly: bool) -> (facts: string)

# Returns the current plan. empty=true means no changes pending.
method Plan() -> (plan: string, len: int)

# Syncs the local source repo to the latest revision.
# Pass revision to pin to a specific ref, leave empty for latest.
method Sync(revision: ?string) -> ()

# Plans and executes an update. Returns number of steps completed.
method Update() -> (steps: int)

error SyncFailed(message: string)
error PlanFailed(message: string)
error ExecutionFailed(message: string, stepsCompleted: int, totalSteps: int)
`
}

// Generated service interface

type VarlinkInterface struct {
	systemsprimamateriamateriaInterface
}

func VarlinkNew(m systemsprimamateriamateriaInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
