name: build
on:
  push:
    branches: ["master"]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: latest # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
          # automatically write this mise.toml file
          mise_toml: |
            [tools]
            age = "latest"
            go = "1.24"
            golangci-lint = "latest"
            "go:golang.org/x/tools/cmd/stringer" = "latest"
      - name: Test with the Go CLI
        run: make test
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: git.saintnet.tech
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push
        env:
          IMAGE_NAME: materia
          REGISTRY: git.saintnet.tech
          REPO_OWNER: stryan
        run: "podman manifest create ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}\n podman build --manifest ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME} --platform linux/amd64,linux/arm64 -f Containerfile .\npodman push ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}:latest          \n"
