name: build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  IMAGE_REGISTRY: git.saintnet.tech/${{ github.repository_owner }}
  MISE_ENV: ci
  TAG: "${{ github.ref_name == 'master' && 'latest' || github.ref_name  }}"
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          # version: "latest" # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
      - name: Setup qemu
        run: "docker run --rm --privileged multiarch/qemu-user-static --reset -p yes"
      - name: Setup docker buildx
        run: "docker buildx create --name multi-platform-builder --driver docker-container --use"
      - name: Build container
        run: |
          echo "${{ REGISTRY_PASSWORD }}" | docker login -u "${{ REGISTRY_USER }}" --password-stdin git.saintnet.tech
          mise ci
      - name: Logout registry
        run: docker logout git.saintnet.tech
