---
name: build
on:
  push:
    branches: [master]
    tags-ignore: ['**']
    paths:
      - internal/**
      - cmd/**
      - scripts/**
      - pkg/**
      - .gitea/workflows/build.yml
      - mise.toml
      - go.mod
      - go.sum
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  IMAGE_REGISTRY: ${{ vars.FORGE }}/${{ github.actor }}
  MISE_ENV: ci
  FNOX_PROFILE: ci
  FNOX_AGE_KEY: ${{secrets.MATERIA_AGE_KEY}}
  RYUK_CONTAINER_PRIVILEGED: true
  DOCKER_HOST: unix:///var/run/podman/podman.sock
  CONTAINER_HOST: unix:///var/run/podman/podman.sock
  BUILDAH_ISOLATION: chroot
jobs:
  build:
    runs-on: materia
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git init .
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}" \
            fetch --tags origin "${GITHUB_REF}"
          git checkout --detach FETCH_HEAD
          git update-ref "${GITHUB_REF}" HEAD
      - name: Setup mise
        run: |
          mise trust
          mise install
      - name: Run unit tests
        run: mise run test
      - name: Build binaries
        run: mise run build
      - name: Run integration tests
        run: mise run integration -k
      - name: Login to registry
        run: mise x -- fnox get REGISTRY_TOKEN | podman login "${{ vars.FORGE }}"
          -u "$(mise x -- fnox get REGISTRY_USER)" --password-stdin
      - name: Login to ghcr registry
        run: mise x -- fnox get GH_TOKEN | podman login ghcr.io -u "$(mise x -- fnox
          get GH_USER)" --password-stdin
      - name: Copy Registry auths for cosign
        run: mkdir -p ~/.docker && cat /run/containers/0/auth.json > ~/.docker/config.json
      - name: Build container image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASS }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            mise ci-buildah
          else
            mise ci-buildah --no-sign latest ${IMAGE_REGISTRY}/materia ghcr.io/stryan/materia
          fi
      - name: Cleanup leftover containers
        if: always()
        run: mise run clean-test-containers
      - name: Logout registry
        run: podman logout "$IMAGE_REGISTRY"
      - name: Logout registry
        run: podman logout ghcr.io
