name: build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  IMAGE_REGISTRY: git.saintnet.tech/${{ github.repository_owner }}
  MISE_ENV: ci
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          # version: "latest" # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
      - name: Setup qemu
        run: "docker run --rm --privileged multiarch/qemu-user-static --reset -p yes"
      - name: Setup docker buildx
        run: "docker buildx create --use"
      - name: Build container
        run: mise container
      - name: Login to registry
        run: docker login git.saintnet.tech --username ${REGISTRY_USER} --password ${REGISTRY_PASSWORD}
      - name: Push container
        run: docker push git.saintnet.tech/stryan/materia:latest
    # - name: Log in to registry
    #   uses: redhat-actions/podman-login@v1
    #   with:
    #     username: ${{ env.REGISTRY_USER }}
    #     password: ${{ env.REGISTRY_PASSWORD }}
    #     registry: ${{ env.IMAGE_REGISTRY }}
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     tags: "git.saintnet.tech/stryan/materia:latest"
    #     push: true
    #     file: Containerfile
