name: build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          # version: "latest" # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
          # automatically write this mise.toml file
          mise_toml: |
            [tools]
            age = "latest"
            go = "1.24"
            golangci-lint = "latest"
            "go:golang.org/x/tools/cmd/stringer" = "latest"
      - name: Test with the Go CLI
        run: mise test
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: git.saintnet.tech
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: "git.saintnet.tech/stryan/materia:latest"
          push: true
          file: Containerfile
