---
name: release
on:
  push:
    tags: [v*.*.*]
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  IMAGE_REGISTRY: ${{ vars.FORGE }}/${{ github.actor }}
  MISE_ENV: ci
  GITHUB_REPOSITORY: stryan/materia
jobs:
  # Build job
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          # version: "latest"  # [default: latest] mise version to install
          install: true  # [default: true] run `mise install`
          cache: true  # [default: true] cache mise using GitHub's cache
          experimental: true  # [default: false] enable experimental features
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Setup qemu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.FORGE }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build container
        run: |
          export TAG=${{ github.ref_name }}
          mise ci
      - name: Logout registry
        run: docker logout $(IMAGE_REGISTRY)
      - name: Generate github release
        uses: softprops/action-gh-release@v2
        with:
          files: |-
            bin/materia-amd64
            bin/materia-arm64
          make_latest: true
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }}
