---
name: release
on:
  push:
    tags: [v*.*.*]
env:
  IMAGE_REGISTRY: ${{ vars.FORGE }}/${{ github.actor }}
  MISE_ENV: ci
  FNOX_PROFILE: ci
  FNOX_AGE_KEY: ${{secrets.MATERIA_AGE_KEY}}
  RYUK_CONTAINER_PRIVILEGED: true
  DOCKER_HOST: unix:///var/run/podman/podman.sock
  CONTAINER_HOST: unix:///var/run/podman/podman.sock
  BUILDAH_ISOLATION: chroot
jobs:
  # Build job
  build-and-release:
    runs-on: materia
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git init .
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}" \
            fetch --tags origin "${GITHUB_REF}"
          git checkout --detach FETCH_HEAD
          git update-ref "${GITHUB_REF}" HEAD
      - name: Setup mise
        run: |
          mise trust
          mise install
      - name: Run unit tests
        run: mise run test
      - name: Build binaries
        run: mise run build
      - name: Run integration tests
        run: mise run integration -k
      - name: Login to registry
        run: mise x -- fnox get REGISTRY_TOKEN | podman login "${{ vars.FORGE }}"
          -u "$(mise x -- fnox get REGISTRY_USER)" --password-stdin
      - name: Login to ghcr registry
        run: mise x -- fnox get GH_TOKEN | podman login ghcr.io -u "$(mise x -- fnox
          get GH_USER)" --password-stdin
      - name: Build container image and release
        run: mise run ci-release ${{ github.ref_name }}
      - name: Cleanup leftover containers
        if: always()
        run: mise run clean-test-containers
      - name: Logout registry
        run: podman logout "$IMAGE_REGISTRY"
      - name: Logout registry
        run: podman logout ghcr.io
