---
name: release
on:
  push:
    tags: [v*.*.*]
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  IMAGE_REGISTRY: ${{ vars.FORGE }}/${{ github.actor }}
  MISE_ENV: ci
  GITHUB_REPOSITORY: stryan/materia
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CONTAINER_HOST: unix:///var/run/podman/podman.sock
  RYUK_CONTAINER_PRIVILEGED: true
jobs:
  # Build job
  build-and-release:
    runs-on: materia
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git init .
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}" \
            fetch --depth=1 origin "+${GITHUB_REF}:${GITHUB_REF}"
          git checkout --detach FETCH_HEAD
      - name: Setup mise
        run: |
          mise trust
          mise install
      - name: Run unit tests
        run: mise run test
      - name: Build binaries
        run: mise run build
      - name: Run integration tests
        run: mise run integration -k
      - name: Login to registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | podman login "${{ vars.FORGE }}"
          -u "${{ gitea.actor }}" --password-stdin
      - name: Login to ghcr registry
        run: echo "${{ secrets.GH_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}"
          --password-stdin
      - name: Build container image and release
        run: mise run ci-release ${{ github.ref_name }}
      - name: Cleanup leftover containers
        if: always()
        run: mise run clean-test-containers
      - name: Logout registry
        run: podman logout "$IMAGE_REGISTRY"
      - name: Logout registry
        run: podman logout ghcr.io
