# This is a secrets file for the "base" role. Any host with the "base" role will have these secrets accesible to them
[components.beszel-server] # we are not limited to setting secrets for components in the "base" role.
somethingspecial = "here"
