// Code generated by "stringer -type ComponentLifecycle -trimprefix State"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateStale-1]
	_ = x[StateFresh-2]
	_ = x[StateOK-3]
	_ = x[StateMayNeedUpdate-4]
	_ = x[StateNeedUpdate-5]
	_ = x[StateNeedRemoval-6]
	_ = x[StateRemoved-7]
	_ = x[StateRoot-8]
}

const _ComponentLifecycle_name = "UnknownStaleFreshOKMayNeedUpdateNeedUpdateNeedRemovalRemovedRoot"

var _ComponentLifecycle_index = [...]uint8{0, 7, 12, 17, 19, 32, 42, 53, 60, 64}

func (i ComponentLifecycle) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ComponentLifecycle_index)-1 {
		return "ComponentLifecycle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentLifecycle_name[_ComponentLifecycle_index[idx]:_ComponentLifecycle_index[idx+1]]
}
