// Code generated by "stringer -type ResourceType -trimprefix ResourceType"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceTypeUnknown-0]
	_ = x[ResourceTypeComponent-1]
	_ = x[ResourceTypeHost-2]
	_ = x[ResourceTypeContainer-3]
	_ = x[ResourceTypeVolume-4]
	_ = x[ResourceTypePod-5]
	_ = x[ResourceTypeNetwork-6]
	_ = x[ResourceTypeKube-7]
	_ = x[ResourceTypeBuild-8]
	_ = x[ResourceTypeImage-9]
	_ = x[ResourceTypeAppFile-10]
	_ = x[ResourceTypeCombined-11]
	_ = x[ResourceTypeFile-12]
	_ = x[ResourceTypeManifest-13]
	_ = x[ResourceTypeScript-14]
	_ = x[ResourceTypeDirectory-15]
	_ = x[ResourceTypeService-16]
	_ = x[ResourceTypePodmanSecret-17]
}

const _ResourceType_name = "UnknownComponentHostContainerVolumePodNetworkKubeBuildImageAppFileCombinedFileManifestScriptDirectoryServicePodmanSecret"

var _ResourceType_index = [...]uint8{0, 7, 16, 20, 29, 35, 38, 45, 49, 54, 59, 66, 74, 78, 86, 92, 101, 108, 120}

func (i ResourceType) String() string {
	if i >= ResourceType(len(_ResourceType_index)-1) {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
