// Code generated by "stringer -type ResourceType -trimprefix ResourceType"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceTypeUnknown-0]
	_ = x[ResourceTypeComponent-1]
	_ = x[ResourceTypeHost-2]
	_ = x[ResourceTypeContainer-3]
	_ = x[ResourceTypeVolume-4]
	_ = x[ResourceTypePod-5]
	_ = x[ResourceTypeNetwork-6]
	_ = x[ResourceTypeKube-7]
	_ = x[ResourceTypeBuild-8]
	_ = x[ResourceTypeImage-9]
	_ = x[ResourceTypeAppFile-10]
	_ = x[ResourceTypeCombined-11]
	_ = x[ResourceTypeDropinDir-12]
	_ = x[ResourceTypeDropin-13]
	_ = x[ResourceTypeFile-14]
	_ = x[ResourceTypeManifest-15]
	_ = x[ResourceTypeScript-16]
	_ = x[ResourceTypeDirectory-17]
	_ = x[ResourceTypeService-18]
	_ = x[ResourceTypePodmanSecret-19]
}

const _ResourceType_name = "UnknownComponentHostContainerVolumePodNetworkKubeBuildImageAppFileCombinedDropinDirDropinFileManifestScriptDirectoryServicePodmanSecret"

var _ResourceType_index = [...]uint8{0, 7, 16, 20, 29, 35, 38, 45, 49, 54, 59, 66, 74, 83, 89, 93, 101, 107, 116, 123, 135}

func (i ResourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceType_index)-1 {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[idx]:_ResourceType_index[idx+1]]
}
