[Roles.base]  # defines a "role", which is a collection of components that can be assigned as one unit to a host
Components = [
  "beszel-agent",
]  # a nice example component; install the monitoring agent on every node we use

[Hosts.ivy]  # defines the assigned components for host named "ivy"
# for this host, we just assign a role
Roles = ["base"]

[Hosts.warden]
Components = ["beszel-server"]  # you can directly assign components to hosts
Roles = ["base"]
