// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/source"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function for the type MockSource
func (_mock *MockSource) Clean() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSource_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockSource_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
func (_e *MockSource_Expecter) Clean() *MockSource_Clean_Call {
	return &MockSource_Clean_Call{Call: _e.mock.On("Clean")}
}

func (_c *MockSource_Clean_Call) Run(run func()) *MockSource_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Clean_Call) Return(err error) *MockSource_Clean_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSource_Clean_Call) RunAndReturn(run func() error) *MockSource_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockSource
func (_mock *MockSource) Close(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSource_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSource_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockSource_Expecter) Close(context1 any) *MockSource_Close_Call {
	return &MockSource_Close_Call{Call: _e.mock.On("Close", context1)}
}

func (_c *MockSource_Close_Call) Run(run func(context1 context.Context)) *MockSource_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSource_Close_Call) Return(err error) *MockSource_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSource_Close_Call) RunAndReturn(run func(context1 context.Context) error) *MockSource_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type MockSource
func (_mock *MockSource) Inspect() source.SyncInspectReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 source.SyncInspectReport
	if returnFunc, ok := ret.Get(0).(func() source.SyncInspectReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(source.SyncInspectReport)
	}
	return r0
}

// MockSource_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockSource_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
func (_e *MockSource_Expecter) Inspect() *MockSource_Inspect_Call {
	return &MockSource_Inspect_Call{Call: _e.mock.On("Inspect")}
}

func (_c *MockSource_Inspect_Call) Run(run func()) *MockSource_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Inspect_Call) Return(syncInspectReport source.SyncInspectReport) *MockSource_Inspect_Call {
	_c.Call.Return(syncInspectReport)
	return _c
}

func (_c *MockSource_Inspect_Call) RunAndReturn(run func() source.SyncInspectReport) *MockSource_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockSource
func (_mock *MockSource) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockSource_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockSource_Expecter) String() *MockSource_String_Call {
	return &MockSource_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockSource_String_Call) Run(run func()) *MockSource_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_String_Call) Return(s string) *MockSource_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_String_Call) RunAndReturn(run func() string) *MockSource_String_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockSource
func (_mock *MockSource) Sync(context1 context.Context, syncOpts source.SyncOpts) (*source.SyncReport, error) {
	ret := _mock.Called(context1, syncOpts)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *source.SyncReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.SyncOpts) (*source.SyncReport, error)); ok {
		return returnFunc(context1, syncOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.SyncOpts) *source.SyncReport); ok {
		r0 = returnFunc(context1, syncOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*source.SyncReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, source.SyncOpts) error); ok {
		r1 = returnFunc(context1, syncOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSource_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - context1 context.Context
//   - syncOpts source.SyncOpts
func (_e *MockSource_Expecter) Sync(context1 any, syncOpts any) *MockSource_Sync_Call {
	return &MockSource_Sync_Call{Call: _e.mock.On("Sync", context1, syncOpts)}
}

func (_c *MockSource_Sync_Call) Run(run func(context1 context.Context, syncOpts source.SyncOpts)) *MockSource_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 source.SyncOpts
		if args[1] != nil {
			arg1 = args[1].(source.SyncOpts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Sync_Call) Return(syncReport *source.SyncReport, err error) *MockSource_Sync_Call {
	_c.Call.Return(syncReport, err)
	return _c
}

func (_c *MockSource_Sync_Call) RunAndReturn(run func(context1 context.Context, syncOpts source.SyncOpts) (*source.SyncReport, error)) *MockSource_Sync_Call {
	_c.Call.Return(run)
	return _c
}
