// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/containers"
	"primamateria.systems/materia/pkg/services"
)

// NewMockHostStateManager creates a new instance of MockHostStateManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostStateManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostStateManager {
	mock := &MockHostStateManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostStateManager is an autogenerated mock type for the HostStateManager type
type MockHostStateManager struct {
	mock.Mock
}

type MockHostStateManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostStateManager) EXPECT() *MockHostStateManager_Expecter {
	return &MockHostStateManager_Expecter{mock: &_m.Mock}
}

// GetNetwork provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) GetNetwork(context1 context.Context, s string) (*containers.Network, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNetwork")
	}

	var r0 *containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Network, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Network); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_GetNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetwork'
type MockHostStateManager_GetNetwork_Call struct {
	*mock.Call
}

// GetNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostStateManager_Expecter) GetNetwork(context1 any, s any) *MockHostStateManager_GetNetwork_Call {
	return &MockHostStateManager_GetNetwork_Call{Call: _e.mock.On("GetNetwork", context1, s)}
}

func (_c *MockHostStateManager_GetNetwork_Call) Run(run func(context1 context.Context, s string)) *MockHostStateManager_GetNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostStateManager_GetNetwork_Call) Return(network *containers.Network, err error) *MockHostStateManager_GetNetwork_Call {
	_c.Call.Return(network, err)
	return _c
}

func (_c *MockHostStateManager_GetNetwork_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Network, error)) *MockHostStateManager_GetNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) GetService(context1 context.Context, s string) (*services.Service, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 *services.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*services.Service, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *services.Service); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockHostStateManager_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostStateManager_Expecter) GetService(context1 any, s any) *MockHostStateManager_GetService_Call {
	return &MockHostStateManager_GetService_Call{Call: _e.mock.On("GetService", context1, s)}
}

func (_c *MockHostStateManager_GetService_Call) Run(run func(context1 context.Context, s string)) *MockHostStateManager_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostStateManager_GetService_Call) Return(service *services.Service, err error) *MockHostStateManager_GetService_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockHostStateManager_GetService_Call) RunAndReturn(run func(context1 context.Context, s string) (*services.Service, error)) *MockHostStateManager_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) GetVolume(context1 context.Context, s string) (*containers.Volume, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 *containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Volume, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Volume); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockHostStateManager_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostStateManager_Expecter) GetVolume(context1 any, s any) *MockHostStateManager_GetVolume_Call {
	return &MockHostStateManager_GetVolume_Call{Call: _e.mock.On("GetVolume", context1, s)}
}

func (_c *MockHostStateManager_GetVolume_Call) Run(run func(context1 context.Context, s string)) *MockHostStateManager_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostStateManager_GetVolume_Call) Return(volume *containers.Volume, err error) *MockHostStateManager_GetVolume_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockHostStateManager_GetVolume_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Volume, error)) *MockHostStateManager_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) ListImages(context1 context.Context) ([]*containers.Image, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []*containers.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Image, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Image); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockHostStateManager_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostStateManager_Expecter) ListImages(context1 any) *MockHostStateManager_ListImages_Call {
	return &MockHostStateManager_ListImages_Call{Call: _e.mock.On("ListImages", context1)}
}

func (_c *MockHostStateManager_ListImages_Call) Run(run func(context1 context.Context)) *MockHostStateManager_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostStateManager_ListImages_Call) Return(images []*containers.Image, err error) *MockHostStateManager_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockHostStateManager_ListImages_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Image, error)) *MockHostStateManager_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) ListNetworks(context1 context.Context) ([]*containers.Network, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []*containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Network, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Network); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockHostStateManager_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostStateManager_Expecter) ListNetworks(context1 any) *MockHostStateManager_ListNetworks_Call {
	return &MockHostStateManager_ListNetworks_Call{Call: _e.mock.On("ListNetworks", context1)}
}

func (_c *MockHostStateManager_ListNetworks_Call) Run(run func(context1 context.Context)) *MockHostStateManager_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostStateManager_ListNetworks_Call) Return(networks []*containers.Network, err error) *MockHostStateManager_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *MockHostStateManager_ListNetworks_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Network, error)) *MockHostStateManager_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type MockHostStateManager
func (_mock *MockHostStateManager) ListVolumes(context1 context.Context) ([]*containers.Volume, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []*containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Volume, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Volume); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostStateManager_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockHostStateManager_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostStateManager_Expecter) ListVolumes(context1 any) *MockHostStateManager_ListVolumes_Call {
	return &MockHostStateManager_ListVolumes_Call{Call: _e.mock.On("ListVolumes", context1)}
}

func (_c *MockHostStateManager_ListVolumes_Call) Run(run func(context1 context.Context)) *MockHostStateManager_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostStateManager_ListVolumes_Call) Return(volumes []*containers.Volume, err error) *MockHostStateManager_ListVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockHostStateManager_ListVolumes_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Volume, error)) *MockHostStateManager_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}
