// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function for the type MockRepository
func (_mock *MockRepository) Clean(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockRepository_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Clean(ctx interface{}) *MockRepository_Clean_Call {
	return &MockRepository_Clean_Call{Call: _e.mock.On("Clean", ctx)}
}

func (_c *MockRepository_Clean_Call) Run(run func(ctx context.Context)) *MockRepository_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Clean_Call) Return(err error) *MockRepository_Clean_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Clean_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockRepository
func (_mock *MockRepository) Exists(ctx context.Context, path string) (bool, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockRepository_Expecter) Exists(ctx interface{}, path interface{}) *MockRepository_Exists_Call {
	return &MockRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, path)}
}

func (_c *MockRepository_Exists_Call) Run(run func(ctx context.Context, path string)) *MockRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Exists_Call) Return(b bool, err error) *MockRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, path string) (bool, error)) *MockRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockRepository_Expecter) Get(ctx interface{}, path interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, path string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(s string, err error) *MockRepository_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function for the type MockRepository
func (_mock *MockRepository) Install(ctx context.Context, path string, data []byte) error {
	ret := _mock.Called(ctx, path, data)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockRepository_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data []byte
func (_e *MockRepository_Expecter) Install(ctx interface{}, path interface{}, data interface{}) *MockRepository_Install_Call {
	return &MockRepository_Install_Call{Call: _e.mock.On("Install", ctx, path, data)}
}

func (_c *MockRepository_Install_Call) Run(run func(ctx context.Context, path string, data []byte)) *MockRepository_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Install_Call) Return(err error) *MockRepository_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Install_Call) RunAndReturn(run func(ctx context.Context, path string, data []byte) error) *MockRepository_Install_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) List(ctx interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(strings []string, err error) *MockRepository_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockRepository
func (_mock *MockRepository) Remove(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockRepository_Expecter) Remove(ctx interface{}, path interface{}) *MockRepository_Remove_Call {
	return &MockRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, path)}
}

func (_c *MockRepository_Remove_Call) Run(run func(ctx context.Context, path string)) *MockRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Remove_Call) Return(err error) *MockRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
