// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/internal/attributes"
)

// NewMockAttributesEngine creates a new instance of MockAttributesEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributesEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributesEngine {
	mock := &MockAttributesEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributesEngine is an autogenerated mock type for the AttributesEngine type
type MockAttributesEngine struct {
	mock.Mock
}

type MockAttributesEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributesEngine) EXPECT() *MockAttributesEngine_Expecter {
	return &MockAttributesEngine_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type MockAttributesEngine
func (_mock *MockAttributesEngine) Lookup(context1 context.Context, attributesFilter attributes.AttributesFilter) (map[string]any, error) {
	ret := _mock.Called(context1, attributesFilter)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attributes.AttributesFilter) (map[string]any, error)); ok {
		return returnFunc(context1, attributesFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, attributes.AttributesFilter) map[string]any); ok {
		r0 = returnFunc(context1, attributesFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, attributes.AttributesFilter) error); ok {
		r1 = returnFunc(context1, attributesFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributesEngine_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockAttributesEngine_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - context1 context.Context
//   - attributesFilter attributes.AttributesFilter
func (_e *MockAttributesEngine_Expecter) Lookup(context1 interface{}, attributesFilter interface{}) *MockAttributesEngine_Lookup_Call {
	return &MockAttributesEngine_Lookup_Call{Call: _e.mock.On("Lookup", context1, attributesFilter)}
}

func (_c *MockAttributesEngine_Lookup_Call) Run(run func(context1 context.Context, attributesFilter attributes.AttributesFilter)) *MockAttributesEngine_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attributes.AttributesFilter
		if args[1] != nil {
			arg1 = args[1].(attributes.AttributesFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributesEngine_Lookup_Call) Return(stringToV map[string]any, err error) *MockAttributesEngine_Lookup_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockAttributesEngine_Lookup_Call) RunAndReturn(run func(context1 context.Context, attributesFilter attributes.AttributesFilter) (map[string]any, error)) *MockAttributesEngine_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
