// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLocker creates a new instance of MockLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocker {
	mock := &MockLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocker is an autogenerated mock type for the Locker type
type MockLocker struct {
	mock.Mock
}

type MockLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocker) EXPECT() *MockLocker_Expecter {
	return &MockLocker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockLocker
func (_mock *MockLocker) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLocker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLocker_Expecter) Close() *MockLocker_Close_Call {
	return &MockLocker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLocker_Close_Call) Run(run func()) *MockLocker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocker_Close_Call) Return(err error) *MockLocker_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocker_Close_Call) RunAndReturn(run func() error) *MockLocker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockLocker
func (_mock *MockLocker) Lock() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockLocker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
func (_e *MockLocker_Expecter) Lock() *MockLocker_Lock_Call {
	return &MockLocker_Lock_Call{Call: _e.mock.On("Lock")}
}

func (_c *MockLocker_Lock_Call) Run(run func()) *MockLocker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocker_Lock_Call) Return(err error) *MockLocker_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocker_Lock_Call) RunAndReturn(run func() error) *MockLocker_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// LockOrWait provides a mock function for the type MockLocker
func (_mock *MockLocker) LockOrWait(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for LockOrWait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocker_LockOrWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockOrWait'
type MockLocker_LockOrWait_Call struct {
	*mock.Call
}

// LockOrWait is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockLocker_Expecter) LockOrWait(context1 interface{}) *MockLocker_LockOrWait_Call {
	return &MockLocker_LockOrWait_Call{Call: _e.mock.On("LockOrWait", context1)}
}

func (_c *MockLocker_LockOrWait_Call) Run(run func(context1 context.Context)) *MockLocker_LockOrWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocker_LockOrWait_Call) Return(err error) *MockLocker_LockOrWait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocker_LockOrWait_Call) RunAndReturn(run func(context1 context.Context) error) *MockLocker_LockOrWait_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockLocker
func (_mock *MockLocker) Unlock() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocker_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockLocker_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
func (_e *MockLocker_Expecter) Unlock() *MockLocker_Unlock_Call {
	return &MockLocker_Unlock_Call{Call: _e.mock.On("Unlock")}
}

func (_c *MockLocker_Unlock_Call) Run(run func()) *MockLocker_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLocker_Unlock_Call) Return(err error) *MockLocker_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocker_Unlock_Call) RunAndReturn(run func() error) *MockLocker_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
