// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/components"
	"primamateria.systems/materia/pkg/manifests"
	"primamateria.systems/materia/pkg/source"
)

// NewMockSourceManager creates a new instance of MockSourceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceManager {
	mock := &MockSourceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSourceManager is an autogenerated mock type for the SourceManager type
type MockSourceManager struct {
	mock.Mock
}

type MockSourceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceManager) EXPECT() *MockSourceManager_Expecter {
	return &MockSourceManager_Expecter{mock: &_m.Mock}
}

// AddSource provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) AddSource(source1 source.Source, syncOpts *source.SyncOpts, syncReport *source.SyncReport, b bool) error {
	ret := _mock.Called(source1, syncOpts, syncReport, b)

	if len(ret) == 0 {
		panic("no return value specified for AddSource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(source.Source, *source.SyncOpts, *source.SyncReport, bool) error); ok {
		r0 = returnFunc(source1, syncOpts, syncReport, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceManager_AddSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSource'
type MockSourceManager_AddSource_Call struct {
	*mock.Call
}

// AddSource is a helper method to define mock.On call
//   - source1 source.Source
//   - syncOpts *source.SyncOpts
//   - syncReport *source.SyncReport
//   - b bool
func (_e *MockSourceManager_Expecter) AddSource(source1 interface{}, syncOpts interface{}, syncReport interface{}, b interface{}) *MockSourceManager_AddSource_Call {
	return &MockSourceManager_AddSource_Call{Call: _e.mock.On("AddSource", source1, syncOpts, syncReport, b)}
}

func (_c *MockSourceManager_AddSource_Call) Run(run func(source1 source.Source, syncOpts *source.SyncOpts, syncReport *source.SyncReport, b bool)) *MockSourceManager_AddSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 source.Source
		if args[0] != nil {
			arg0 = args[0].(source.Source)
		}
		var arg1 *source.SyncOpts
		if args[1] != nil {
			arg1 = args[1].(*source.SyncOpts)
		}
		var arg2 *source.SyncReport
		if args[2] != nil {
			arg2 = args[2].(*source.SyncReport)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSourceManager_AddSource_Call) Return(err error) *MockSourceManager_AddSource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceManager_AddSource_Call) RunAndReturn(run func(source1 source.Source, syncOpts *source.SyncOpts, syncReport *source.SyncReport, b bool) error) *MockSourceManager_AddSource_Call {
	_c.Call.Return(run)
	return _c
}

// Clean provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) Clean() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceManager_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockSourceManager_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
func (_e *MockSourceManager_Expecter) Clean() *MockSourceManager_Clean_Call {
	return &MockSourceManager_Clean_Call{Call: _e.mock.On("Clean")}
}

func (_c *MockSourceManager_Clean_Call) Run(run func()) *MockSourceManager_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSourceManager_Clean_Call) Return(err error) *MockSourceManager_Clean_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceManager_Clean_Call) RunAndReturn(run func() error) *MockSourceManager_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// ComponentExists provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) ComponentExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ComponentExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_ComponentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentExists'
type MockSourceManager_ComponentExists_Call struct {
	*mock.Call
}

// ComponentExists is a helper method to define mock.On call
//   - s string
func (_e *MockSourceManager_Expecter) ComponentExists(s interface{}) *MockSourceManager_ComponentExists_Call {
	return &MockSourceManager_ComponentExists_Call{Call: _e.mock.On("ComponentExists", s)}
}

func (_c *MockSourceManager_ComponentExists_Call) Run(run func(s string)) *MockSourceManager_ComponentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_ComponentExists_Call) Return(b bool, err error) *MockSourceManager_ComponentExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSourceManager_ComponentExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockSourceManager_ComponentExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) GetComponent(s string) (*components.Component, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 *components.Component
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*components.Component, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *components.Component); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.Component)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockSourceManager_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - s string
func (_e *MockSourceManager_Expecter) GetComponent(s interface{}) *MockSourceManager_GetComponent_Call {
	return &MockSourceManager_GetComponent_Call{Call: _e.mock.On("GetComponent", s)}
}

func (_c *MockSourceManager_GetComponent_Call) Run(run func(s string)) *MockSourceManager_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_GetComponent_Call) Return(component *components.Component, err error) *MockSourceManager_GetComponent_Call {
	_c.Call.Return(component, err)
	return _c
}

func (_c *MockSourceManager_GetComponent_Call) RunAndReturn(run func(s string) (*components.Component, error)) *MockSourceManager_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) GetManifest(component *components.Component) (*manifests.ComponentManifest, error) {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *manifests.ComponentManifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) (*manifests.ComponentManifest, error)); ok {
		return returnFunc(component)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component) *manifests.ComponentManifest); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manifests.ComponentManifest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component) error); ok {
		r1 = returnFunc(component)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type MockSourceManager_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockSourceManager_Expecter) GetManifest(component interface{}) *MockSourceManager_GetManifest_Call {
	return &MockSourceManager_GetManifest_Call{Call: _e.mock.On("GetManifest", component)}
}

func (_c *MockSourceManager_GetManifest_Call) Run(run func(component *components.Component)) *MockSourceManager_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_GetManifest_Call) Return(componentManifest *manifests.ComponentManifest, err error) *MockSourceManager_GetManifest_Call {
	_c.Call.Return(componentManifest, err)
	return _c
}

func (_c *MockSourceManager_GetManifest_Call) RunAndReturn(run func(component *components.Component) (*manifests.ComponentManifest, error)) *MockSourceManager_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) GetResource(component *components.Component, s string) (components.Resource, error) {
	ret := _mock.Called(component, s)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 components.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component, string) (components.Resource, error)); ok {
		return returnFunc(component, s)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component, string) components.Resource); ok {
		r0 = returnFunc(component, s)
	} else {
		r0 = ret.Get(0).(components.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component, string) error); ok {
		r1 = returnFunc(component, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type MockSourceManager_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - component *components.Component
//   - s string
func (_e *MockSourceManager_Expecter) GetResource(component interface{}, s interface{}) *MockSourceManager_GetResource_Call {
	return &MockSourceManager_GetResource_Call{Call: _e.mock.On("GetResource", component, s)}
}

func (_c *MockSourceManager_GetResource_Call) Run(run func(component *components.Component, s string)) *MockSourceManager_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceManager_GetResource_Call) Return(resource components.Resource, err error) *MockSourceManager_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockSourceManager_GetResource_Call) RunAndReturn(run func(component *components.Component, s string) (components.Resource, error)) *MockSourceManager_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentNames provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) ListComponentNames() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListComponentNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_ListComponentNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentNames'
type MockSourceManager_ListComponentNames_Call struct {
	*mock.Call
}

// ListComponentNames is a helper method to define mock.On call
func (_e *MockSourceManager_Expecter) ListComponentNames() *MockSourceManager_ListComponentNames_Call {
	return &MockSourceManager_ListComponentNames_Call{Call: _e.mock.On("ListComponentNames")}
}

func (_c *MockSourceManager_ListComponentNames_Call) Run(run func()) *MockSourceManager_ListComponentNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSourceManager_ListComponentNames_Call) Return(strings []string, err error) *MockSourceManager_ListComponentNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSourceManager_ListComponentNames_Call) RunAndReturn(run func() ([]string, error)) *MockSourceManager_ListComponentNames_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) ListResources(component *components.Component) ([]components.Resource, error) {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []components.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) ([]components.Resource, error)); ok {
		return returnFunc(component)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component) []components.Resource); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component) error); ok {
		r1 = returnFunc(component)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockSourceManager_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockSourceManager_Expecter) ListResources(component interface{}) *MockSourceManager_ListResources_Call {
	return &MockSourceManager_ListResources_Call{Call: _e.mock.On("ListResources", component)}
}

func (_c *MockSourceManager_ListResources_Call) Run(run func(component *components.Component)) *MockSourceManager_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_ListResources_Call) Return(resources []components.Resource, err error) *MockSourceManager_ListResources_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *MockSourceManager_ListResources_Call) RunAndReturn(run func(component *components.Component) ([]components.Resource, error)) *MockSourceManager_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// LoadManifest provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) LoadManifest(s string) (*manifests.MateriaManifest, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for LoadManifest")
	}

	var r0 *manifests.MateriaManifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*manifests.MateriaManifest, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *manifests.MateriaManifest); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manifests.MateriaManifest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_LoadManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadManifest'
type MockSourceManager_LoadManifest_Call struct {
	*mock.Call
}

// LoadManifest is a helper method to define mock.On call
//   - s string
func (_e *MockSourceManager_Expecter) LoadManifest(s interface{}) *MockSourceManager_LoadManifest_Call {
	return &MockSourceManager_LoadManifest_Call{Call: _e.mock.On("LoadManifest", s)}
}

func (_c *MockSourceManager_LoadManifest_Call) Run(run func(s string)) *MockSourceManager_LoadManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_LoadManifest_Call) Return(materiaManifest *manifests.MateriaManifest, err error) *MockSourceManager_LoadManifest_Call {
	_c.Call.Return(materiaManifest, err)
	return _c
}

func (_c *MockSourceManager_LoadManifest_Call) RunAndReturn(run func(s string) (*manifests.MateriaManifest, error)) *MockSourceManager_LoadManifest_Call {
	_c.Call.Return(run)
	return _c
}

// ReadResource provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) ReadResource(resource components.Resource) (string, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for ReadResource")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(components.Resource) (string, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(components.Resource) string); ok {
		r0 = returnFunc(resource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(components.Resource) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceManager_ReadResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadResource'
type MockSourceManager_ReadResource_Call struct {
	*mock.Call
}

// ReadResource is a helper method to define mock.On call
//   - resource components.Resource
func (_e *MockSourceManager_Expecter) ReadResource(resource interface{}) *MockSourceManager_ReadResource_Call {
	return &MockSourceManager_ReadResource_Call{Call: _e.mock.On("ReadResource", resource)}
}

func (_c *MockSourceManager_ReadResource_Call) Run(run func(resource components.Resource)) *MockSourceManager_ReadResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 components.Resource
		if args[0] != nil {
			arg0 = args[0].(components.Resource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_ReadResource_Call) Return(s string, err error) *MockSourceManager_ReadResource_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSourceManager_ReadResource_Call) RunAndReturn(run func(resource components.Resource) (string, error)) *MockSourceManager_ReadResource_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) Rollback(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceManager_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockSourceManager_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockSourceManager_Expecter) Rollback(context1 interface{}) *MockSourceManager_Rollback_Call {
	return &MockSourceManager_Rollback_Call{Call: _e.mock.On("Rollback", context1)}
}

func (_c *MockSourceManager_Rollback_Call) Run(run func(context1 context.Context)) *MockSourceManager_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSourceManager_Rollback_Call) Return(err error) *MockSourceManager_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceManager_Rollback_Call) RunAndReturn(run func(context1 context.Context) error) *MockSourceManager_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockSourceManager
func (_mock *MockSourceManager) Sync(context1 context.Context, syncOpts *source.SyncOpts) error {
	ret := _mock.Called(context1, syncOpts)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *source.SyncOpts) error); ok {
		r0 = returnFunc(context1, syncOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSourceManager_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSourceManager_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - context1 context.Context
//   - syncOpts *source.SyncOpts
func (_e *MockSourceManager_Expecter) Sync(context1 interface{}, syncOpts interface{}) *MockSourceManager_Sync_Call {
	return &MockSourceManager_Sync_Call{Call: _e.mock.On("Sync", context1, syncOpts)}
}

func (_c *MockSourceManager_Sync_Call) Run(run func(context1 context.Context, syncOpts *source.SyncOpts)) *MockSourceManager_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *source.SyncOpts
		if args[1] != nil {
			arg1 = args[1].(*source.SyncOpts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceManager_Sync_Call) Return(err error) *MockSourceManager_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSourceManager_Sync_Call) RunAndReturn(run func(context1 context.Context, syncOpts *source.SyncOpts) error) *MockSourceManager_Sync_Call {
	_c.Call.Return(run)
	return _c
}
