// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/services"
)

// NewMockServiceManager creates a new instance of MockServiceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceManager {
	mock := &MockServiceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceManager is an autogenerated mock type for the ServiceManager type
type MockServiceManager struct {
	mock.Mock
}

type MockServiceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceManager) EXPECT() *MockServiceManager_Expecter {
	return &MockServiceManager_Expecter{mock: &_m.Mock}
}

// ApplyService provides a mock function for the type MockServiceManager
func (_mock *MockServiceManager) ApplyService(context1 context.Context, s string, serviceAction services.ServiceAction, n int) error {
	ret := _mock.Called(context1, s, serviceAction, n)

	if len(ret) == 0 {
		panic("no return value specified for ApplyService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, services.ServiceAction, int) error); ok {
		r0 = returnFunc(context1, s, serviceAction, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceManager_ApplyService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyService'
type MockServiceManager_ApplyService_Call struct {
	*mock.Call
}

// ApplyService is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - serviceAction services.ServiceAction
//   - n int
func (_e *MockServiceManager_Expecter) ApplyService(context1 interface{}, s interface{}, serviceAction interface{}, n interface{}) *MockServiceManager_ApplyService_Call {
	return &MockServiceManager_ApplyService_Call{Call: _e.mock.On("ApplyService", context1, s, serviceAction, n)}
}

func (_c *MockServiceManager_ApplyService_Call) Run(run func(context1 context.Context, s string, serviceAction services.ServiceAction, n int)) *MockServiceManager_ApplyService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 services.ServiceAction
		if args[2] != nil {
			arg2 = args[2].(services.ServiceAction)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceManager_ApplyService_Call) Return(err error) *MockServiceManager_ApplyService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceManager_ApplyService_Call) RunAndReturn(run func(context1 context.Context, s string, serviceAction services.ServiceAction, n int) error) *MockServiceManager_ApplyService_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockServiceManager
func (_mock *MockServiceManager) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockServiceManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockServiceManager_Expecter) Close() *MockServiceManager_Close_Call {
	return &MockServiceManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockServiceManager_Close_Call) Run(run func()) *MockServiceManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceManager_Close_Call) Return(err error) *MockServiceManager_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceManager_Close_Call) RunAndReturn(run func() error) *MockServiceManager_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockServiceManager
func (_mock *MockServiceManager) GetService(context1 context.Context, s string) (*services.Service, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 *services.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*services.Service, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *services.Service); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceManager_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockServiceManager_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockServiceManager_Expecter) GetService(context1 interface{}, s interface{}) *MockServiceManager_GetService_Call {
	return &MockServiceManager_GetService_Call{Call: _e.mock.On("GetService", context1, s)}
}

func (_c *MockServiceManager_GetService_Call) Run(run func(context1 context.Context, s string)) *MockServiceManager_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceManager_GetService_Call) Return(service *services.Service, err error) *MockServiceManager_GetService_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockServiceManager_GetService_Call) RunAndReturn(run func(context1 context.Context, s string) (*services.Service, error)) *MockServiceManager_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// RunOneshotCommand provides a mock function for the type MockServiceManager
func (_mock *MockServiceManager) RunOneshotCommand(context1 context.Context, n int, s string, strings []string) error {
	ret := _mock.Called(context1, n, s, strings)

	if len(ret) == 0 {
		panic("no return value specified for RunOneshotCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, []string) error); ok {
		r0 = returnFunc(context1, n, s, strings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceManager_RunOneshotCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOneshotCommand'
type MockServiceManager_RunOneshotCommand_Call struct {
	*mock.Call
}

// RunOneshotCommand is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
//   - s string
//   - strings []string
func (_e *MockServiceManager_Expecter) RunOneshotCommand(context1 interface{}, n interface{}, s interface{}, strings interface{}) *MockServiceManager_RunOneshotCommand_Call {
	return &MockServiceManager_RunOneshotCommand_Call{Call: _e.mock.On("RunOneshotCommand", context1, n, s, strings)}
}

func (_c *MockServiceManager_RunOneshotCommand_Call) Run(run func(context1 context.Context, n int, s string, strings []string)) *MockServiceManager_RunOneshotCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceManager_RunOneshotCommand_Call) Return(err error) *MockServiceManager_RunOneshotCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceManager_RunOneshotCommand_Call) RunAndReturn(run func(context1 context.Context, n int, s string, strings []string) error) *MockServiceManager_RunOneshotCommand_Call {
	_c.Call.Return(run)
	return _c
}

// WaitUntilState provides a mock function for the type MockServiceManager
func (_mock *MockServiceManager) WaitUntilState(context1 context.Context, s string, serviceState services.ServiceState, n int) error {
	ret := _mock.Called(context1, s, serviceState, n)

	if len(ret) == 0 {
		panic("no return value specified for WaitUntilState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, services.ServiceState, int) error); ok {
		r0 = returnFunc(context1, s, serviceState, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceManager_WaitUntilState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUntilState'
type MockServiceManager_WaitUntilState_Call struct {
	*mock.Call
}

// WaitUntilState is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - serviceState services.ServiceState
//   - n int
func (_e *MockServiceManager_Expecter) WaitUntilState(context1 interface{}, s interface{}, serviceState interface{}, n interface{}) *MockServiceManager_WaitUntilState_Call {
	return &MockServiceManager_WaitUntilState_Call{Call: _e.mock.On("WaitUntilState", context1, s, serviceState, n)}
}

func (_c *MockServiceManager_WaitUntilState_Call) Run(run func(context1 context.Context, s string, serviceState services.ServiceState, n int)) *MockServiceManager_WaitUntilState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 services.ServiceState
		if args[2] != nil {
			arg2 = args[2].(services.ServiceState)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceManager_WaitUntilState_Call) Return(err error) *MockServiceManager_WaitUntilState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceManager_WaitUntilState_Call) RunAndReturn(run func(context1 context.Context, s string, serviceState services.ServiceState, n int) error) *MockServiceManager_WaitUntilState_Call {
	_c.Call.Return(run)
	return _c
}
