// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFactsProvider creates a new instance of MockFactsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactsProvider {
	mock := &MockFactsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFactsProvider is an autogenerated mock type for the FactsProvider type
type MockFactsProvider struct {
	mock.Mock
}

type MockFactsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactsProvider) EXPECT() *MockFactsProvider_Expecter {
	return &MockFactsProvider_Expecter{mock: &_m.Mock}
}

// GetHostname provides a mock function for the type MockFactsProvider
func (_mock *MockFactsProvider) GetHostname() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHostname")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFactsProvider_GetHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostname'
type MockFactsProvider_GetHostname_Call struct {
	*mock.Call
}

// GetHostname is a helper method to define mock.On call
func (_e *MockFactsProvider_Expecter) GetHostname() *MockFactsProvider_GetHostname_Call {
	return &MockFactsProvider_GetHostname_Call{Call: _e.mock.On("GetHostname")}
}

func (_c *MockFactsProvider_GetHostname_Call) Run(run func()) *MockFactsProvider_GetHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFactsProvider_GetHostname_Call) Return(s string) *MockFactsProvider_GetHostname_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFactsProvider_GetHostname_Call) RunAndReturn(run func() string) *MockFactsProvider_GetHostname_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterfaces provides a mock function for the type MockFactsProvider
func (_mock *MockFactsProvider) GetInterfaces() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInterfaces")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockFactsProvider_GetInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterfaces'
type MockFactsProvider_GetInterfaces_Call struct {
	*mock.Call
}

// GetInterfaces is a helper method to define mock.On call
func (_e *MockFactsProvider_Expecter) GetInterfaces() *MockFactsProvider_GetInterfaces_Call {
	return &MockFactsProvider_GetInterfaces_Call{Call: _e.mock.On("GetInterfaces")}
}

func (_c *MockFactsProvider_GetInterfaces_Call) Run(run func()) *MockFactsProvider_GetInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFactsProvider_GetInterfaces_Call) Return(strings []string) *MockFactsProvider_GetInterfaces_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockFactsProvider_GetInterfaces_Call) RunAndReturn(run func() []string) *MockFactsProvider_GetInterfaces_Call {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function for the type MockFactsProvider
func (_mock *MockFactsProvider) Lookup(s string) (any, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFactsProvider_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockFactsProvider_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - s string
func (_e *MockFactsProvider_Expecter) Lookup(s interface{}) *MockFactsProvider_Lookup_Call {
	return &MockFactsProvider_Lookup_Call{Call: _e.mock.On("Lookup", s)}
}

func (_c *MockFactsProvider_Lookup_Call) Run(run func(s string)) *MockFactsProvider_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFactsProvider_Lookup_Call) Return(v any, err error) *MockFactsProvider_Lookup_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFactsProvider_Lookup_Call) RunAndReturn(run func(s string) (any, error)) *MockFactsProvider_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
