// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockRepository
func (_mock *MockRepository) Install(ctx context.Context, path string, data []byte) error {
	ret := _mock.Called(ctx, path, data)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockRepository_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data []byte
func (_e *MockRepository_Expecter) Install(ctx any, path any, data any) *MockRepository_Install_Call {
	return &MockRepository_Install_Call{Call: _e.mock.On("Install", ctx, path, data)}
}

func (_c *MockRepository_Install_Call) Run(run func(ctx context.Context, path string, data []byte)) *MockRepository_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Install_Call) Return(err error) *MockRepository_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Install_Call) RunAndReturn(run func(ctx context.Context, path string, data []byte) error) *MockRepository_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockRepository
func (_mock *MockRepository) Remove(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockRepository_Expecter) Remove(ctx any, path any) *MockRepository_Remove_Call {
	return &MockRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, path)}
}

func (_c *MockRepository_Remove_Call) Run(run func(ctx context.Context, path string)) *MockRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Remove_Call) Return(err error) *MockRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
