// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/components"
	"primamateria.systems/materia/pkg/containers"
	"primamateria.systems/materia/pkg/manifests"
	"primamateria.systems/materia/pkg/services"
)

// NewMockHostManager creates a new instance of MockHostManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostManager {
	mock := &MockHostManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostManager is an autogenerated mock type for the HostManager type
type MockHostManager struct {
	mock.Mock
}

type MockHostManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostManager) EXPECT() *MockHostManager_Expecter {
	return &MockHostManager_Expecter{mock: &_m.Mock}
}

// ApplyService provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ApplyService(context1 context.Context, s string, serviceAction services.ServiceAction, n int) error {
	ret := _mock.Called(context1, s, serviceAction, n)

	if len(ret) == 0 {
		panic("no return value specified for ApplyService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, services.ServiceAction, int) error); ok {
		r0 = returnFunc(context1, s, serviceAction, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_ApplyService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyService'
type MockHostManager_ApplyService_Call struct {
	*mock.Call
}

// ApplyService is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - serviceAction services.ServiceAction
//   - n int
func (_e *MockHostManager_Expecter) ApplyService(context1 interface{}, s interface{}, serviceAction interface{}, n interface{}) *MockHostManager_ApplyService_Call {
	return &MockHostManager_ApplyService_Call{Call: _e.mock.On("ApplyService", context1, s, serviceAction, n)}
}

func (_c *MockHostManager_ApplyService_Call) Run(run func(context1 context.Context, s string, serviceAction services.ServiceAction, n int)) *MockHostManager_ApplyService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 services.ServiceAction
		if args[2] != nil {
			arg2 = args[2].(services.ServiceAction)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHostManager_ApplyService_Call) Return(err error) *MockHostManager_ApplyService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_ApplyService_Call) RunAndReturn(run func(context1 context.Context, s string, serviceAction services.ServiceAction, n int) error) *MockHostManager_ApplyService_Call {
	_c.Call.Return(run)
	return _c
}

// Clean provides a mock function for the type MockHostManager
func (_mock *MockHostManager) Clean() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type MockHostManager_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
func (_e *MockHostManager_Expecter) Clean() *MockHostManager_Clean_Call {
	return &MockHostManager_Clean_Call{Call: _e.mock.On("Clean")}
}

func (_c *MockHostManager_Clean_Call) Run(run func()) *MockHostManager_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostManager_Clean_Call) Return(err error) *MockHostManager_Clean_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_Clean_Call) RunAndReturn(run func() error) *MockHostManager_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// ComponentExists provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ComponentExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ComponentExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ComponentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentExists'
type MockHostManager_ComponentExists_Call struct {
	*mock.Call
}

// ComponentExists is a helper method to define mock.On call
//   - s string
func (_e *MockHostManager_Expecter) ComponentExists(s interface{}) *MockHostManager_ComponentExists_Call {
	return &MockHostManager_ComponentExists_Call{Call: _e.mock.On("ComponentExists", s)}
}

func (_c *MockHostManager_ComponentExists_Call) Run(run func(s string)) *MockHostManager_ComponentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ComponentExists_Call) Return(b bool, err error) *MockHostManager_ComponentExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHostManager_ComponentExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockHostManager_ComponentExists_Call {
	_c.Call.Return(run)
	return _c
}

// DumpVolume provides a mock function for the type MockHostManager
func (_mock *MockHostManager) DumpVolume(context1 context.Context, volume *containers.Volume, s string) error {
	ret := _mock.Called(context1, volume, s)

	if len(ret) == 0 {
		panic("no return value specified for DumpVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume, string) error); ok {
		r0 = returnFunc(context1, volume, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_DumpVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DumpVolume'
type MockHostManager_DumpVolume_Call struct {
	*mock.Call
}

// DumpVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
//   - s string
func (_e *MockHostManager_Expecter) DumpVolume(context1 interface{}, volume interface{}, s interface{}) *MockHostManager_DumpVolume_Call {
	return &MockHostManager_DumpVolume_Call{Call: _e.mock.On("DumpVolume", context1, volume, s)}
}

func (_c *MockHostManager_DumpVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume, s string)) *MockHostManager_DumpVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostManager_DumpVolume_Call) Return(err error) *MockHostManager_DumpVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_DumpVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume, s string) error) *MockHostManager_DumpVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContainer provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ExecContainer(context1 context.Context, s string, strings ...string) error {
	var tmpRet mock.Arguments
	if len(strings) > 0 {
		tmpRet = _mock.Called(context1, s, strings)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(context1, s, strings...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_ExecContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContainer'
type MockHostManager_ExecContainer_Call struct {
	*mock.Call
}

// ExecContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - strings ...string
func (_e *MockHostManager_Expecter) ExecContainer(context1 interface{}, s interface{}, strings ...interface{}) *MockHostManager_ExecContainer_Call {
	return &MockHostManager_ExecContainer_Call{Call: _e.mock.On("ExecContainer",
		append([]interface{}{context1, s}, strings...)...)}
}

func (_c *MockHostManager_ExecContainer_Call) Run(run func(context1 context.Context, s string, strings ...string)) *MockHostManager_ExecContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHostManager_ExecContainer_Call) Return(err error) *MockHostManager_ExecContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_ExecContainer_Call) RunAndReturn(run func(context1 context.Context, s string, strings ...string) error) *MockHostManager_ExecContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetComponent(s string) (*components.Component, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 *components.Component
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*components.Component, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *components.Component); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.Component)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockHostManager_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - s string
func (_e *MockHostManager_Expecter) GetComponent(s interface{}) *MockHostManager_GetComponent_Call {
	return &MockHostManager_GetComponent_Call{Call: _e.mock.On("GetComponent", s)}
}

func (_c *MockHostManager_GetComponent_Call) Run(run func(s string)) *MockHostManager_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_GetComponent_Call) Return(component *components.Component, err error) *MockHostManager_GetComponent_Call {
	_c.Call.Return(component, err)
	return _c
}

func (_c *MockHostManager_GetComponent_Call) RunAndReturn(run func(s string) (*components.Component, error)) *MockHostManager_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainer provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetContainer(context1 context.Context, s string) (*containers.Container, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 *containers.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Container, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Container); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type MockHostManager_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) GetContainer(context1 interface{}, s interface{}) *MockHostManager_GetContainer_Call {
	return &MockHostManager_GetContainer_Call{Call: _e.mock.On("GetContainer", context1, s)}
}

func (_c *MockHostManager_GetContainer_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetContainer_Call) Return(container *containers.Container, err error) *MockHostManager_GetContainer_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockHostManager_GetContainer_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Container, error)) *MockHostManager_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetHostname provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetHostname() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHostname")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHostManager_GetHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostname'
type MockHostManager_GetHostname_Call struct {
	*mock.Call
}

// GetHostname is a helper method to define mock.On call
func (_e *MockHostManager_Expecter) GetHostname() *MockHostManager_GetHostname_Call {
	return &MockHostManager_GetHostname_Call{Call: _e.mock.On("GetHostname")}
}

func (_c *MockHostManager_GetHostname_Call) Run(run func()) *MockHostManager_GetHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostManager_GetHostname_Call) Return(s string) *MockHostManager_GetHostname_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHostManager_GetHostname_Call) RunAndReturn(run func() string) *MockHostManager_GetHostname_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterfaces provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetInterfaces() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInterfaces")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockHostManager_GetInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterfaces'
type MockHostManager_GetInterfaces_Call struct {
	*mock.Call
}

// GetInterfaces is a helper method to define mock.On call
func (_e *MockHostManager_Expecter) GetInterfaces() *MockHostManager_GetInterfaces_Call {
	return &MockHostManager_GetInterfaces_Call{Call: _e.mock.On("GetInterfaces")}
}

func (_c *MockHostManager_GetInterfaces_Call) Run(run func()) *MockHostManager_GetInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostManager_GetInterfaces_Call) Return(strings []string) *MockHostManager_GetInterfaces_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockHostManager_GetInterfaces_Call) RunAndReturn(run func() []string) *MockHostManager_GetInterfaces_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetManifest(component *components.Component) (*manifests.ComponentManifest, error) {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *manifests.ComponentManifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) (*manifests.ComponentManifest, error)); ok {
		return returnFunc(component)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component) *manifests.ComponentManifest); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manifests.ComponentManifest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component) error); ok {
		r1 = returnFunc(component)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type MockHostManager_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) GetManifest(component interface{}) *MockHostManager_GetManifest_Call {
	return &MockHostManager_GetManifest_Call{Call: _e.mock.On("GetManifest", component)}
}

func (_c *MockHostManager_GetManifest_Call) Run(run func(component *components.Component)) *MockHostManager_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_GetManifest_Call) Return(componentManifest *manifests.ComponentManifest, err error) *MockHostManager_GetManifest_Call {
	_c.Call.Return(componentManifest, err)
	return _c
}

func (_c *MockHostManager_GetManifest_Call) RunAndReturn(run func(component *components.Component) (*manifests.ComponentManifest, error)) *MockHostManager_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetwork provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetNetwork(context1 context.Context, s string) (*containers.Network, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNetwork")
	}

	var r0 *containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Network, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Network); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetwork'
type MockHostManager_GetNetwork_Call struct {
	*mock.Call
}

// GetNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) GetNetwork(context1 interface{}, s interface{}) *MockHostManager_GetNetwork_Call {
	return &MockHostManager_GetNetwork_Call{Call: _e.mock.On("GetNetwork", context1, s)}
}

func (_c *MockHostManager_GetNetwork_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_GetNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetNetwork_Call) Return(network *containers.Network, err error) *MockHostManager_GetNetwork_Call {
	_c.Call.Return(network, err)
	return _c
}

func (_c *MockHostManager_GetNetwork_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Network, error)) *MockHostManager_GetNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetResource(component *components.Component, s string) (components.Resource, error) {
	ret := _mock.Called(component, s)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 components.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component, string) (components.Resource, error)); ok {
		return returnFunc(component, s)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component, string) components.Resource); ok {
		r0 = returnFunc(component, s)
	} else {
		r0 = ret.Get(0).(components.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component, string) error); ok {
		r1 = returnFunc(component, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type MockHostManager_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - component *components.Component
//   - s string
func (_e *MockHostManager_Expecter) GetResource(component interface{}, s interface{}) *MockHostManager_GetResource_Call {
	return &MockHostManager_GetResource_Call{Call: _e.mock.On("GetResource", component, s)}
}

func (_c *MockHostManager_GetResource_Call) Run(run func(component *components.Component, s string)) *MockHostManager_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetResource_Call) Return(resource components.Resource, err error) *MockHostManager_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockHostManager_GetResource_Call) RunAndReturn(run func(component *components.Component, s string) (components.Resource, error)) *MockHostManager_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetSecret(context1 context.Context, s string) (*containers.PodmanSecret, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *containers.PodmanSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.PodmanSecret, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.PodmanSecret); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.PodmanSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockHostManager_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) GetSecret(context1 interface{}, s interface{}) *MockHostManager_GetSecret_Call {
	return &MockHostManager_GetSecret_Call{Call: _e.mock.On("GetSecret", context1, s)}
}

func (_c *MockHostManager_GetSecret_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetSecret_Call) Return(podmanSecret *containers.PodmanSecret, err error) *MockHostManager_GetSecret_Call {
	_c.Call.Return(podmanSecret, err)
	return _c
}

func (_c *MockHostManager_GetSecret_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.PodmanSecret, error)) *MockHostManager_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetService(context1 context.Context, s string) (*services.Service, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 *services.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*services.Service, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *services.Service); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockHostManager_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) GetService(context1 interface{}, s interface{}) *MockHostManager_GetService_Call {
	return &MockHostManager_GetService_Call{Call: _e.mock.On("GetService", context1, s)}
}

func (_c *MockHostManager_GetService_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetService_Call) Return(service *services.Service, err error) *MockHostManager_GetService_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockHostManager_GetService_Call) RunAndReturn(run func(context1 context.Context, s string) (*services.Service, error)) *MockHostManager_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type MockHostManager
func (_mock *MockHostManager) GetVolume(context1 context.Context, s string) (*containers.Volume, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 *containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Volume, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Volume); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockHostManager_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) GetVolume(context1 interface{}, s interface{}) *MockHostManager_GetVolume_Call {
	return &MockHostManager_GetVolume_Call{Call: _e.mock.On("GetVolume", context1, s)}
}

func (_c *MockHostManager_GetVolume_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_GetVolume_Call) Return(volume *containers.Volume, err error) *MockHostManager_GetVolume_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockHostManager_GetVolume_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Volume, error)) *MockHostManager_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ImportVolume provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ImportVolume(context1 context.Context, volume *containers.Volume, s string) error {
	ret := _mock.Called(context1, volume, s)

	if len(ret) == 0 {
		panic("no return value specified for ImportVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume, string) error); ok {
		r0 = returnFunc(context1, volume, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_ImportVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportVolume'
type MockHostManager_ImportVolume_Call struct {
	*mock.Call
}

// ImportVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
//   - s string
func (_e *MockHostManager_Expecter) ImportVolume(context1 interface{}, volume interface{}, s interface{}) *MockHostManager_ImportVolume_Call {
	return &MockHostManager_ImportVolume_Call{Call: _e.mock.On("ImportVolume", context1, volume, s)}
}

func (_c *MockHostManager_ImportVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume, s string)) *MockHostManager_ImportVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostManager_ImportVolume_Call) Return(err error) *MockHostManager_ImportVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_ImportVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume, s string) error) *MockHostManager_ImportVolume_Call {
	_c.Call.Return(run)
	return _c
}

// InstallComponent provides a mock function for the type MockHostManager
func (_mock *MockHostManager) InstallComponent(component *components.Component) error {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for InstallComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) error); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_InstallComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallComponent'
type MockHostManager_InstallComponent_Call struct {
	*mock.Call
}

// InstallComponent is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) InstallComponent(component interface{}) *MockHostManager_InstallComponent_Call {
	return &MockHostManager_InstallComponent_Call{Call: _e.mock.On("InstallComponent", component)}
}

func (_c *MockHostManager_InstallComponent_Call) Run(run func(component *components.Component)) *MockHostManager_InstallComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_InstallComponent_Call) Return(err error) *MockHostManager_InstallComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_InstallComponent_Call) RunAndReturn(run func(component *components.Component) error) *MockHostManager_InstallComponent_Call {
	_c.Call.Return(run)
	return _c
}

// InstallResource provides a mock function for the type MockHostManager
func (_mock *MockHostManager) InstallResource(resource components.Resource, bytes []byte) error {
	ret := _mock.Called(resource, bytes)

	if len(ret) == 0 {
		panic("no return value specified for InstallResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(components.Resource, []byte) error); ok {
		r0 = returnFunc(resource, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_InstallResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallResource'
type MockHostManager_InstallResource_Call struct {
	*mock.Call
}

// InstallResource is a helper method to define mock.On call
//   - resource components.Resource
//   - bytes []byte
func (_e *MockHostManager_Expecter) InstallResource(resource interface{}, bytes interface{}) *MockHostManager_InstallResource_Call {
	return &MockHostManager_InstallResource_Call{Call: _e.mock.On("InstallResource", resource, bytes)}
}

func (_c *MockHostManager_InstallResource_Call) Run(run func(resource components.Resource, bytes []byte)) *MockHostManager_InstallResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 components.Resource
		if args[0] != nil {
			arg0 = args[0].(components.Resource)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_InstallResource_Call) Return(err error) *MockHostManager_InstallResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_InstallResource_Call) RunAndReturn(run func(resource components.Resource, bytes []byte) error) *MockHostManager_InstallResource_Call {
	_c.Call.Return(run)
	return _c
}

// InstallScript provides a mock function for the type MockHostManager
func (_mock *MockHostManager) InstallScript(context1 context.Context, s string, bytes []byte) error {
	ret := _mock.Called(context1, s, bytes)

	if len(ret) == 0 {
		panic("no return value specified for InstallScript")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(context1, s, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_InstallScript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallScript'
type MockHostManager_InstallScript_Call struct {
	*mock.Call
}

// InstallScript is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - bytes []byte
func (_e *MockHostManager_Expecter) InstallScript(context1 interface{}, s interface{}, bytes interface{}) *MockHostManager_InstallScript_Call {
	return &MockHostManager_InstallScript_Call{Call: _e.mock.On("InstallScript", context1, s, bytes)}
}

func (_c *MockHostManager_InstallScript_Call) Run(run func(context1 context.Context, s string, bytes []byte)) *MockHostManager_InstallScript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostManager_InstallScript_Call) Return(err error) *MockHostManager_InstallScript_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_InstallScript_Call) RunAndReturn(run func(context1 context.Context, s string, bytes []byte) error) *MockHostManager_InstallScript_Call {
	_c.Call.Return(run)
	return _c
}

// InstallUnit provides a mock function for the type MockHostManager
func (_mock *MockHostManager) InstallUnit(context1 context.Context, s string, bytes []byte) error {
	ret := _mock.Called(context1, s, bytes)

	if len(ret) == 0 {
		panic("no return value specified for InstallUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(context1, s, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_InstallUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallUnit'
type MockHostManager_InstallUnit_Call struct {
	*mock.Call
}

// InstallUnit is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - bytes []byte
func (_e *MockHostManager_Expecter) InstallUnit(context1 interface{}, s interface{}, bytes interface{}) *MockHostManager_InstallUnit_Call {
	return &MockHostManager_InstallUnit_Call{Call: _e.mock.On("InstallUnit", context1, s, bytes)}
}

func (_c *MockHostManager_InstallUnit_Call) Run(run func(context1 context.Context, s string, bytes []byte)) *MockHostManager_InstallUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostManager_InstallUnit_Call) Return(err error) *MockHostManager_InstallUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_InstallUnit_Call) RunAndReturn(run func(context1 context.Context, s string, bytes []byte) error) *MockHostManager_InstallUnit_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentNames provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListComponentNames() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListComponentNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListComponentNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentNames'
type MockHostManager_ListComponentNames_Call struct {
	*mock.Call
}

// ListComponentNames is a helper method to define mock.On call
func (_e *MockHostManager_Expecter) ListComponentNames() *MockHostManager_ListComponentNames_Call {
	return &MockHostManager_ListComponentNames_Call{Call: _e.mock.On("ListComponentNames")}
}

func (_c *MockHostManager_ListComponentNames_Call) Run(run func()) *MockHostManager_ListComponentNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostManager_ListComponentNames_Call) Return(strings []string, err error) *MockHostManager_ListComponentNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockHostManager_ListComponentNames_Call) RunAndReturn(run func() ([]string, error)) *MockHostManager_ListComponentNames_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListContainers(context1 context.Context, containerListFilter containers.ContainerListFilter) ([]*containers.Container, error) {
	ret := _mock.Called(context1, containerListFilter)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []*containers.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerListFilter) ([]*containers.Container, error)); ok {
		return returnFunc(context1, containerListFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerListFilter) []*containers.Container); ok {
		r0 = returnFunc(context1, containerListFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, containers.ContainerListFilter) error); ok {
		r1 = returnFunc(context1, containerListFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockHostManager_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - context1 context.Context
//   - containerListFilter containers.ContainerListFilter
func (_e *MockHostManager_Expecter) ListContainers(context1 interface{}, containerListFilter interface{}) *MockHostManager_ListContainers_Call {
	return &MockHostManager_ListContainers_Call{Call: _e.mock.On("ListContainers", context1, containerListFilter)}
}

func (_c *MockHostManager_ListContainers_Call) Run(run func(context1 context.Context, containerListFilter containers.ContainerListFilter)) *MockHostManager_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 containers.ContainerListFilter
		if args[1] != nil {
			arg1 = args[1].(containers.ContainerListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_ListContainers_Call) Return(containers1 []*containers.Container, err error) *MockHostManager_ListContainers_Call {
	_c.Call.Return(containers1, err)
	return _c
}

func (_c *MockHostManager_ListContainers_Call) RunAndReturn(run func(context1 context.Context, containerListFilter containers.ContainerListFilter) ([]*containers.Container, error)) *MockHostManager_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListImages(context1 context.Context) ([]*containers.Image, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []*containers.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Image, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Image); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockHostManager_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostManager_Expecter) ListImages(context1 interface{}) *MockHostManager_ListImages_Call {
	return &MockHostManager_ListImages_Call{Call: _e.mock.On("ListImages", context1)}
}

func (_c *MockHostManager_ListImages_Call) Run(run func(context1 context.Context)) *MockHostManager_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ListImages_Call) Return(images []*containers.Image, err error) *MockHostManager_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockHostManager_ListImages_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Image, error)) *MockHostManager_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstalledComponents provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListInstalledComponents() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListInstalledComponents")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListInstalledComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstalledComponents'
type MockHostManager_ListInstalledComponents_Call struct {
	*mock.Call
}

// ListInstalledComponents is a helper method to define mock.On call
func (_e *MockHostManager_Expecter) ListInstalledComponents() *MockHostManager_ListInstalledComponents_Call {
	return &MockHostManager_ListInstalledComponents_Call{Call: _e.mock.On("ListInstalledComponents")}
}

func (_c *MockHostManager_ListInstalledComponents_Call) Run(run func()) *MockHostManager_ListInstalledComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHostManager_ListInstalledComponents_Call) Return(strings []string, err error) *MockHostManager_ListInstalledComponents_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockHostManager_ListInstalledComponents_Call) RunAndReturn(run func() ([]string, error)) *MockHostManager_ListInstalledComponents_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListNetworks(context1 context.Context) ([]*containers.Network, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []*containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Network, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Network); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockHostManager_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostManager_Expecter) ListNetworks(context1 interface{}) *MockHostManager_ListNetworks_Call {
	return &MockHostManager_ListNetworks_Call{Call: _e.mock.On("ListNetworks", context1)}
}

func (_c *MockHostManager_ListNetworks_Call) Run(run func(context1 context.Context)) *MockHostManager_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ListNetworks_Call) Return(networks []*containers.Network, err error) *MockHostManager_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *MockHostManager_ListNetworks_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Network, error)) *MockHostManager_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListResources(component *components.Component) ([]components.Resource, error) {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []components.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) ([]components.Resource, error)); ok {
		return returnFunc(component)
	}
	if returnFunc, ok := ret.Get(0).(func(*components.Component) []components.Resource); ok {
		r0 = returnFunc(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*components.Component) error); ok {
		r1 = returnFunc(component)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockHostManager_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) ListResources(component interface{}) *MockHostManager_ListResources_Call {
	return &MockHostManager_ListResources_Call{Call: _e.mock.On("ListResources", component)}
}

func (_c *MockHostManager_ListResources_Call) Run(run func(component *components.Component)) *MockHostManager_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ListResources_Call) Return(resources []components.Resource, err error) *MockHostManager_ListResources_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *MockHostManager_ListResources_Call) RunAndReturn(run func(component *components.Component) ([]components.Resource, error)) *MockHostManager_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListSecrets(context1 context.Context) ([]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockHostManager_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostManager_Expecter) ListSecrets(context1 interface{}) *MockHostManager_ListSecrets_Call {
	return &MockHostManager_ListSecrets_Call{Call: _e.mock.On("ListSecrets", context1)}
}

func (_c *MockHostManager_ListSecrets_Call) Run(run func(context1 context.Context)) *MockHostManager_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ListSecrets_Call) Return(strings []string, err error) *MockHostManager_ListSecrets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockHostManager_ListSecrets_Call) RunAndReturn(run func(context1 context.Context) ([]string, error)) *MockHostManager_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ListVolumes(context1 context.Context) ([]*containers.Volume, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []*containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Volume, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Volume); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockHostManager_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHostManager_Expecter) ListVolumes(context1 interface{}) *MockHostManager_ListVolumes_Call {
	return &MockHostManager_ListVolumes_Call{Call: _e.mock.On("ListVolumes", context1)}
}

func (_c *MockHostManager_ListVolumes_Call) Run(run func(context1 context.Context)) *MockHostManager_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ListVolumes_Call) Return(volumes []*containers.Volume, err error) *MockHostManager_ListVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockHostManager_ListVolumes_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Volume, error)) *MockHostManager_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function for the type MockHostManager
func (_mock *MockHostManager) Lookup(s string) (any, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockHostManager_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - s string
func (_e *MockHostManager_Expecter) Lookup(s interface{}) *MockHostManager_Lookup_Call {
	return &MockHostManager_Lookup_Call{Call: _e.mock.On("Lookup", s)}
}

func (_c *MockHostManager_Lookup_Call) Run(run func(s string)) *MockHostManager_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_Lookup_Call) Return(v any, err error) *MockHostManager_Lookup_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockHostManager_Lookup_Call) RunAndReturn(run func(s string) (any, error)) *MockHostManager_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// MountVolume provides a mock function for the type MockHostManager
func (_mock *MockHostManager) MountVolume(context1 context.Context, volume *containers.Volume) error {
	ret := _mock.Called(context1, volume)

	if len(ret) == 0 {
		panic("no return value specified for MountVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume) error); ok {
		r0 = returnFunc(context1, volume)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_MountVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MountVolume'
type MockHostManager_MountVolume_Call struct {
	*mock.Call
}

// MountVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
func (_e *MockHostManager_Expecter) MountVolume(context1 interface{}, volume interface{}) *MockHostManager_MountVolume_Call {
	return &MockHostManager_MountVolume_Call{Call: _e.mock.On("MountVolume", context1, volume)}
}

func (_c *MockHostManager_MountVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume)) *MockHostManager_MountVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_MountVolume_Call) Return(err error) *MockHostManager_MountVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_MountVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume) error) *MockHostManager_MountVolume_Call {
	_c.Call.Return(run)
	return _c
}

// PauseContainer provides a mock function for the type MockHostManager
func (_mock *MockHostManager) PauseContainer(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for PauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_PauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseContainer'
type MockHostManager_PauseContainer_Call struct {
	*mock.Call
}

// PauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) PauseContainer(context1 interface{}, s interface{}) *MockHostManager_PauseContainer_Call {
	return &MockHostManager_PauseContainer_Call{Call: _e.mock.On("PauseContainer", context1, s)}
}

func (_c *MockHostManager_PauseContainer_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_PauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_PauseContainer_Call) Return(err error) *MockHostManager_PauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_PauseContainer_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_PauseContainer_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeComponent provides a mock function for the type MockHostManager
func (_mock *MockHostManager) PurgeComponent(component *components.Component) error {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for PurgeComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) error); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_PurgeComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeComponent'
type MockHostManager_PurgeComponent_Call struct {
	*mock.Call
}

// PurgeComponent is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) PurgeComponent(component interface{}) *MockHostManager_PurgeComponent_Call {
	return &MockHostManager_PurgeComponent_Call{Call: _e.mock.On("PurgeComponent", component)}
}

func (_c *MockHostManager_PurgeComponent_Call) Run(run func(component *components.Component)) *MockHostManager_PurgeComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_PurgeComponent_Call) Return(err error) *MockHostManager_PurgeComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_PurgeComponent_Call) RunAndReturn(run func(component *components.Component) error) *MockHostManager_PurgeComponent_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeComponentByName provides a mock function for the type MockHostManager
func (_mock *MockHostManager) PurgeComponentByName(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for PurgeComponentByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_PurgeComponentByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeComponentByName'
type MockHostManager_PurgeComponentByName_Call struct {
	*mock.Call
}

// PurgeComponentByName is a helper method to define mock.On call
//   - s string
func (_e *MockHostManager_Expecter) PurgeComponentByName(s interface{}) *MockHostManager_PurgeComponentByName_Call {
	return &MockHostManager_PurgeComponentByName_Call{Call: _e.mock.On("PurgeComponentByName", s)}
}

func (_c *MockHostManager_PurgeComponentByName_Call) Run(run func(s string)) *MockHostManager_PurgeComponentByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_PurgeComponentByName_Call) Return(err error) *MockHostManager_PurgeComponentByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_PurgeComponentByName_Call) RunAndReturn(run func(s string) error) *MockHostManager_PurgeComponentByName_Call {
	_c.Call.Return(run)
	return _c
}

// ReadResource provides a mock function for the type MockHostManager
func (_mock *MockHostManager) ReadResource(resource components.Resource) (string, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for ReadResource")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(components.Resource) (string, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(components.Resource) string); ok {
		r0 = returnFunc(resource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(components.Resource) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostManager_ReadResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadResource'
type MockHostManager_ReadResource_Call struct {
	*mock.Call
}

// ReadResource is a helper method to define mock.On call
//   - resource components.Resource
func (_e *MockHostManager_Expecter) ReadResource(resource interface{}) *MockHostManager_ReadResource_Call {
	return &MockHostManager_ReadResource_Call{Call: _e.mock.On("ReadResource", resource)}
}

func (_c *MockHostManager_ReadResource_Call) Run(run func(resource components.Resource)) *MockHostManager_ReadResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 components.Resource
		if args[0] != nil {
			arg0 = args[0].(components.Resource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_ReadResource_Call) Return(s string, err error) *MockHostManager_ReadResource_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHostManager_ReadResource_Call) RunAndReturn(run func(resource components.Resource) (string, error)) *MockHostManager_ReadResource_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveComponent provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveComponent(component *components.Component) error {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for RemoveComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) error); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveComponent'
type MockHostManager_RemoveComponent_Call struct {
	*mock.Call
}

// RemoveComponent is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) RemoveComponent(component interface{}) *MockHostManager_RemoveComponent_Call {
	return &MockHostManager_RemoveComponent_Call{Call: _e.mock.On("RemoveComponent", component)}
}

func (_c *MockHostManager_RemoveComponent_Call) Run(run func(component *components.Component)) *MockHostManager_RemoveComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveComponent_Call) Return(err error) *MockHostManager_RemoveComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveComponent_Call) RunAndReturn(run func(component *components.Component) error) *MockHostManager_RemoveComponent_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveImage(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type MockHostManager_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) RemoveImage(context1 interface{}, s interface{}) *MockHostManager_RemoveImage_Call {
	return &MockHostManager_RemoveImage_Call{Call: _e.mock.On("RemoveImage", context1, s)}
}

func (_c *MockHostManager_RemoveImage_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveImage_Call) Return(err error) *MockHostManager_RemoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveImage_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNetwork provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveNetwork(context1 context.Context, network *containers.Network) error {
	ret := _mock.Called(context1, network)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Network) error); ok {
		r0 = returnFunc(context1, network)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNetwork'
type MockHostManager_RemoveNetwork_Call struct {
	*mock.Call
}

// RemoveNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - network *containers.Network
func (_e *MockHostManager_Expecter) RemoveNetwork(context1 interface{}, network interface{}) *MockHostManager_RemoveNetwork_Call {
	return &MockHostManager_RemoveNetwork_Call{Call: _e.mock.On("RemoveNetwork", context1, network)}
}

func (_c *MockHostManager_RemoveNetwork_Call) Run(run func(context1 context.Context, network *containers.Network)) *MockHostManager_RemoveNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Network
		if args[1] != nil {
			arg1 = args[1].(*containers.Network)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveNetwork_Call) Return(err error) *MockHostManager_RemoveNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveNetwork_Call) RunAndReturn(run func(context1 context.Context, network *containers.Network) error) *MockHostManager_RemoveNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveResource provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveResource(resource components.Resource) error {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for RemoveResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(components.Resource) error); ok {
		r0 = returnFunc(resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveResource'
type MockHostManager_RemoveResource_Call struct {
	*mock.Call
}

// RemoveResource is a helper method to define mock.On call
//   - resource components.Resource
func (_e *MockHostManager_Expecter) RemoveResource(resource interface{}) *MockHostManager_RemoveResource_Call {
	return &MockHostManager_RemoveResource_Call{Call: _e.mock.On("RemoveResource", resource)}
}

func (_c *MockHostManager_RemoveResource_Call) Run(run func(resource components.Resource)) *MockHostManager_RemoveResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 components.Resource
		if args[0] != nil {
			arg0 = args[0].(components.Resource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveResource_Call) Return(err error) *MockHostManager_RemoveResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveResource_Call) RunAndReturn(run func(resource components.Resource) error) *MockHostManager_RemoveResource_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveScript provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveScript(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveScript")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveScript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveScript'
type MockHostManager_RemoveScript_Call struct {
	*mock.Call
}

// RemoveScript is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) RemoveScript(context1 interface{}, s interface{}) *MockHostManager_RemoveScript_Call {
	return &MockHostManager_RemoveScript_Call{Call: _e.mock.On("RemoveScript", context1, s)}
}

func (_c *MockHostManager_RemoveScript_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_RemoveScript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveScript_Call) Return(err error) *MockHostManager_RemoveScript_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveScript_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_RemoveScript_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSecret provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveSecret(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSecret'
type MockHostManager_RemoveSecret_Call struct {
	*mock.Call
}

// RemoveSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) RemoveSecret(context1 interface{}, s interface{}) *MockHostManager_RemoveSecret_Call {
	return &MockHostManager_RemoveSecret_Call{Call: _e.mock.On("RemoveSecret", context1, s)}
}

func (_c *MockHostManager_RemoveSecret_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_RemoveSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveSecret_Call) Return(err error) *MockHostManager_RemoveSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveSecret_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_RemoveSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUnit provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveUnit(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUnit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveUnit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUnit'
type MockHostManager_RemoveUnit_Call struct {
	*mock.Call
}

// RemoveUnit is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) RemoveUnit(context1 interface{}, s interface{}) *MockHostManager_RemoveUnit_Call {
	return &MockHostManager_RemoveUnit_Call{Call: _e.mock.On("RemoveUnit", context1, s)}
}

func (_c *MockHostManager_RemoveUnit_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_RemoveUnit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveUnit_Call) Return(err error) *MockHostManager_RemoveUnit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveUnit_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_RemoveUnit_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVolume provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RemoveVolume(context1 context.Context, volume *containers.Volume) error {
	ret := _mock.Called(context1, volume)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume) error); ok {
		r0 = returnFunc(context1, volume)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RemoveVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVolume'
type MockHostManager_RemoveVolume_Call struct {
	*mock.Call
}

// RemoveVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
func (_e *MockHostManager_Expecter) RemoveVolume(context1 interface{}, volume interface{}) *MockHostManager_RemoveVolume_Call {
	return &MockHostManager_RemoveVolume_Call{Call: _e.mock.On("RemoveVolume", context1, volume)}
}

func (_c *MockHostManager_RemoveVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume)) *MockHostManager_RemoveVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_RemoveVolume_Call) Return(err error) *MockHostManager_RemoveVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RemoveVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume) error) *MockHostManager_RemoveVolume_Call {
	_c.Call.Return(run)
	return _c
}

// RunOneshotCommand provides a mock function for the type MockHostManager
func (_mock *MockHostManager) RunOneshotCommand(context1 context.Context, n int, s string, strings []string) error {
	ret := _mock.Called(context1, n, s, strings)

	if len(ret) == 0 {
		panic("no return value specified for RunOneshotCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, []string) error); ok {
		r0 = returnFunc(context1, n, s, strings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_RunOneshotCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOneshotCommand'
type MockHostManager_RunOneshotCommand_Call struct {
	*mock.Call
}

// RunOneshotCommand is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
//   - s string
//   - strings []string
func (_e *MockHostManager_Expecter) RunOneshotCommand(context1 interface{}, n interface{}, s interface{}, strings interface{}) *MockHostManager_RunOneshotCommand_Call {
	return &MockHostManager_RunOneshotCommand_Call{Call: _e.mock.On("RunOneshotCommand", context1, n, s, strings)}
}

func (_c *MockHostManager_RunOneshotCommand_Call) Run(run func(context1 context.Context, n int, s string, strings []string)) *MockHostManager_RunOneshotCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHostManager_RunOneshotCommand_Call) Return(err error) *MockHostManager_RunOneshotCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_RunOneshotCommand_Call) RunAndReturn(run func(context1 context.Context, n int, s string, strings []string) error) *MockHostManager_RunOneshotCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SecretName provides a mock function for the type MockHostManager
func (_mock *MockHostManager) SecretName(s string) string {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for SecretName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHostManager_SecretName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretName'
type MockHostManager_SecretName_Call struct {
	*mock.Call
}

// SecretName is a helper method to define mock.On call
//   - s string
func (_e *MockHostManager_Expecter) SecretName(s interface{}) *MockHostManager_SecretName_Call {
	return &MockHostManager_SecretName_Call{Call: _e.mock.On("SecretName", s)}
}

func (_c *MockHostManager_SecretName_Call) Run(run func(s string)) *MockHostManager_SecretName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_SecretName_Call) Return(s1 string) *MockHostManager_SecretName_Call {
	_c.Call.Return(s1)
	return _c
}

func (_c *MockHostManager_SecretName_Call) RunAndReturn(run func(s string) string) *MockHostManager_SecretName_Call {
	_c.Call.Return(run)
	return _c
}

// UnpauseContainer provides a mock function for the type MockHostManager
func (_mock *MockHostManager) UnpauseContainer(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for UnpauseContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_UnpauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseContainer'
type MockHostManager_UnpauseContainer_Call struct {
	*mock.Call
}

// UnpauseContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockHostManager_Expecter) UnpauseContainer(context1 interface{}, s interface{}) *MockHostManager_UnpauseContainer_Call {
	return &MockHostManager_UnpauseContainer_Call{Call: _e.mock.On("UnpauseContainer", context1, s)}
}

func (_c *MockHostManager_UnpauseContainer_Call) Run(run func(context1 context.Context, s string)) *MockHostManager_UnpauseContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostManager_UnpauseContainer_Call) Return(err error) *MockHostManager_UnpauseContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_UnpauseContainer_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockHostManager_UnpauseContainer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponent provides a mock function for the type MockHostManager
func (_mock *MockHostManager) UpdateComponent(component *components.Component) error {
	ret := _mock.Called(component)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*components.Component) error); ok {
		r0 = returnFunc(component)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_UpdateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponent'
type MockHostManager_UpdateComponent_Call struct {
	*mock.Call
}

// UpdateComponent is a helper method to define mock.On call
//   - component *components.Component
func (_e *MockHostManager_Expecter) UpdateComponent(component interface{}) *MockHostManager_UpdateComponent_Call {
	return &MockHostManager_UpdateComponent_Call{Call: _e.mock.On("UpdateComponent", component)}
}

func (_c *MockHostManager_UpdateComponent_Call) Run(run func(component *components.Component)) *MockHostManager_UpdateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *components.Component
		if args[0] != nil {
			arg0 = args[0].(*components.Component)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHostManager_UpdateComponent_Call) Return(err error) *MockHostManager_UpdateComponent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_UpdateComponent_Call) RunAndReturn(run func(component *components.Component) error) *MockHostManager_UpdateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// WaitUntilState provides a mock function for the type MockHostManager
func (_mock *MockHostManager) WaitUntilState(context1 context.Context, s string, s1 string, n int) error {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for WaitUntilState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_WaitUntilState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUntilState'
type MockHostManager_WaitUntilState_Call struct {
	*mock.Call
}

// WaitUntilState is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int
func (_e *MockHostManager_Expecter) WaitUntilState(context1 interface{}, s interface{}, s1 interface{}, n interface{}) *MockHostManager_WaitUntilState_Call {
	return &MockHostManager_WaitUntilState_Call{Call: _e.mock.On("WaitUntilState", context1, s, s1, n)}
}

func (_c *MockHostManager_WaitUntilState_Call) Run(run func(context1 context.Context, s string, s1 string, n int)) *MockHostManager_WaitUntilState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHostManager_WaitUntilState_Call) Return(err error) *MockHostManager_WaitUntilState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_WaitUntilState_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int) error) *MockHostManager_WaitUntilState_Call {
	_c.Call.Return(run)
	return _c
}

// WriteSecret provides a mock function for the type MockHostManager
func (_mock *MockHostManager) WriteSecret(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for WriteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostManager_WriteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSecret'
type MockHostManager_WriteSecret_Call struct {
	*mock.Call
}

// WriteSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockHostManager_Expecter) WriteSecret(context1 interface{}, s interface{}, s1 interface{}) *MockHostManager_WriteSecret_Call {
	return &MockHostManager_WriteSecret_Call{Call: _e.mock.On("WriteSecret", context1, s, s1)}
}

func (_c *MockHostManager_WriteSecret_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockHostManager_WriteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHostManager_WriteSecret_Call) Return(err error) *MockHostManager_WriteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostManager_WriteSecret_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *MockHostManager_WriteSecret_Call {
	_c.Call.Return(run)
	return _c
}
