// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"primamateria.systems/materia/pkg/containers"
)

// NewMockContainerManager creates a new instance of MockContainerManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerManager {
	mock := &MockContainerManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainerManager is an autogenerated mock type for the ContainerManager type
type MockContainerManager struct {
	mock.Mock
}

type MockContainerManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainerManager) EXPECT() *MockContainerManager_Expecter {
	return &MockContainerManager_Expecter{mock: &_m.Mock}
}

// DumpVolume provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) DumpVolume(context1 context.Context, volume *containers.Volume, s string) error {
	ret := _mock.Called(context1, volume, s)

	if len(ret) == 0 {
		panic("no return value specified for DumpVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume, string) error); ok {
		r0 = returnFunc(context1, volume, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_DumpVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DumpVolume'
type MockContainerManager_DumpVolume_Call struct {
	*mock.Call
}

// DumpVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
//   - s string
func (_e *MockContainerManager_Expecter) DumpVolume(context1 interface{}, volume interface{}, s interface{}) *MockContainerManager_DumpVolume_Call {
	return &MockContainerManager_DumpVolume_Call{Call: _e.mock.On("DumpVolume", context1, volume, s)}
}

func (_c *MockContainerManager_DumpVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume, s string)) *MockContainerManager_DumpVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainerManager_DumpVolume_Call) Return(err error) *MockContainerManager_DumpVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_DumpVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume, s string) error) *MockContainerManager_DumpVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContainer provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ExecContainer(context1 context.Context, s string, strings ...string) error {
	var tmpRet mock.Arguments
	if len(strings) > 0 {
		tmpRet = _mock.Called(context1, s, strings)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(context1, s, strings...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_ExecContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContainer'
type MockContainerManager_ExecContainer_Call struct {
	*mock.Call
}

// ExecContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - strings ...string
func (_e *MockContainerManager_Expecter) ExecContainer(context1 interface{}, s interface{}, strings ...interface{}) *MockContainerManager_ExecContainer_Call {
	return &MockContainerManager_ExecContainer_Call{Call: _e.mock.On("ExecContainer",
		append([]interface{}{context1, s}, strings...)...)}
}

func (_c *MockContainerManager_ExecContainer_Call) Run(run func(context1 context.Context, s string, strings ...string)) *MockContainerManager_ExecContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockContainerManager_ExecContainer_Call) Return(err error) *MockContainerManager_ExecContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_ExecContainer_Call) RunAndReturn(run func(context1 context.Context, s string, strings ...string) error) *MockContainerManager_ExecContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainer provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) GetContainer(context1 context.Context, s string) (*containers.Container, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 *containers.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Container, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Container); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type MockContainerManager_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) GetContainer(context1 interface{}, s interface{}) *MockContainerManager_GetContainer_Call {
	return &MockContainerManager_GetContainer_Call{Call: _e.mock.On("GetContainer", context1, s)}
}

func (_c *MockContainerManager_GetContainer_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_GetContainer_Call) Return(container *containers.Container, err error) *MockContainerManager_GetContainer_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockContainerManager_GetContainer_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Container, error)) *MockContainerManager_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetwork provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) GetNetwork(context1 context.Context, s string) (*containers.Network, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNetwork")
	}

	var r0 *containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Network, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Network); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_GetNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetwork'
type MockContainerManager_GetNetwork_Call struct {
	*mock.Call
}

// GetNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) GetNetwork(context1 interface{}, s interface{}) *MockContainerManager_GetNetwork_Call {
	return &MockContainerManager_GetNetwork_Call{Call: _e.mock.On("GetNetwork", context1, s)}
}

func (_c *MockContainerManager_GetNetwork_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_GetNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_GetNetwork_Call) Return(network *containers.Network, err error) *MockContainerManager_GetNetwork_Call {
	_c.Call.Return(network, err)
	return _c
}

func (_c *MockContainerManager_GetNetwork_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Network, error)) *MockContainerManager_GetNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) GetSecret(context1 context.Context, s string) (*containers.PodmanSecret, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *containers.PodmanSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.PodmanSecret, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.PodmanSecret); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.PodmanSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockContainerManager_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) GetSecret(context1 interface{}, s interface{}) *MockContainerManager_GetSecret_Call {
	return &MockContainerManager_GetSecret_Call{Call: _e.mock.On("GetSecret", context1, s)}
}

func (_c *MockContainerManager_GetSecret_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_GetSecret_Call) Return(podmanSecret *containers.PodmanSecret, err error) *MockContainerManager_GetSecret_Call {
	_c.Call.Return(podmanSecret, err)
	return _c
}

func (_c *MockContainerManager_GetSecret_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.PodmanSecret, error)) *MockContainerManager_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) GetVolume(context1 context.Context, s string) (*containers.Volume, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 *containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*containers.Volume, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *containers.Volume); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockContainerManager_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) GetVolume(context1 interface{}, s interface{}) *MockContainerManager_GetVolume_Call {
	return &MockContainerManager_GetVolume_Call{Call: _e.mock.On("GetVolume", context1, s)}
}

func (_c *MockContainerManager_GetVolume_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_GetVolume_Call) Return(volume *containers.Volume, err error) *MockContainerManager_GetVolume_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *MockContainerManager_GetVolume_Call) RunAndReturn(run func(context1 context.Context, s string) (*containers.Volume, error)) *MockContainerManager_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ImportVolume provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ImportVolume(context1 context.Context, volume *containers.Volume, s string) error {
	ret := _mock.Called(context1, volume, s)

	if len(ret) == 0 {
		panic("no return value specified for ImportVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume, string) error); ok {
		r0 = returnFunc(context1, volume, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_ImportVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportVolume'
type MockContainerManager_ImportVolume_Call struct {
	*mock.Call
}

// ImportVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
//   - s string
func (_e *MockContainerManager_Expecter) ImportVolume(context1 interface{}, volume interface{}, s interface{}) *MockContainerManager_ImportVolume_Call {
	return &MockContainerManager_ImportVolume_Call{Call: _e.mock.On("ImportVolume", context1, volume, s)}
}

func (_c *MockContainerManager_ImportVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume, s string)) *MockContainerManager_ImportVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainerManager_ImportVolume_Call) Return(err error) *MockContainerManager_ImportVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_ImportVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume, s string) error) *MockContainerManager_ImportVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ListContainers(context1 context.Context, containerListFilter containers.ContainerListFilter) ([]*containers.Container, error) {
	ret := _mock.Called(context1, containerListFilter)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []*containers.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerListFilter) ([]*containers.Container, error)); ok {
		return returnFunc(context1, containerListFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, containers.ContainerListFilter) []*containers.Container); ok {
		r0 = returnFunc(context1, containerListFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, containers.ContainerListFilter) error); ok {
		r1 = returnFunc(context1, containerListFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockContainerManager_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - context1 context.Context
//   - containerListFilter containers.ContainerListFilter
func (_e *MockContainerManager_Expecter) ListContainers(context1 interface{}, containerListFilter interface{}) *MockContainerManager_ListContainers_Call {
	return &MockContainerManager_ListContainers_Call{Call: _e.mock.On("ListContainers", context1, containerListFilter)}
}

func (_c *MockContainerManager_ListContainers_Call) Run(run func(context1 context.Context, containerListFilter containers.ContainerListFilter)) *MockContainerManager_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 containers.ContainerListFilter
		if args[1] != nil {
			arg1 = args[1].(containers.ContainerListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_ListContainers_Call) Return(containers1 []*containers.Container, err error) *MockContainerManager_ListContainers_Call {
	_c.Call.Return(containers1, err)
	return _c
}

func (_c *MockContainerManager_ListContainers_Call) RunAndReturn(run func(context1 context.Context, containerListFilter containers.ContainerListFilter) ([]*containers.Container, error)) *MockContainerManager_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ListImages(context1 context.Context) ([]*containers.Image, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []*containers.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Image, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Image); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockContainerManager_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainerManager_Expecter) ListImages(context1 interface{}) *MockContainerManager_ListImages_Call {
	return &MockContainerManager_ListImages_Call{Call: _e.mock.On("ListImages", context1)}
}

func (_c *MockContainerManager_ListImages_Call) Run(run func(context1 context.Context)) *MockContainerManager_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerManager_ListImages_Call) Return(images []*containers.Image, err error) *MockContainerManager_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockContainerManager_ListImages_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Image, error)) *MockContainerManager_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ListNetworks(context1 context.Context) ([]*containers.Network, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []*containers.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Network, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Network); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockContainerManager_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainerManager_Expecter) ListNetworks(context1 interface{}) *MockContainerManager_ListNetworks_Call {
	return &MockContainerManager_ListNetworks_Call{Call: _e.mock.On("ListNetworks", context1)}
}

func (_c *MockContainerManager_ListNetworks_Call) Run(run func(context1 context.Context)) *MockContainerManager_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerManager_ListNetworks_Call) Return(networks []*containers.Network, err error) *MockContainerManager_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *MockContainerManager_ListNetworks_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Network, error)) *MockContainerManager_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ListSecrets(context1 context.Context) ([]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockContainerManager_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainerManager_Expecter) ListSecrets(context1 interface{}) *MockContainerManager_ListSecrets_Call {
	return &MockContainerManager_ListSecrets_Call{Call: _e.mock.On("ListSecrets", context1)}
}

func (_c *MockContainerManager_ListSecrets_Call) Run(run func(context1 context.Context)) *MockContainerManager_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerManager_ListSecrets_Call) Return(strings []string, err error) *MockContainerManager_ListSecrets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockContainerManager_ListSecrets_Call) RunAndReturn(run func(context1 context.Context) ([]string, error)) *MockContainerManager_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) ListVolumes(context1 context.Context) ([]*containers.Volume, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []*containers.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*containers.Volume, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*containers.Volume); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*containers.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerManager_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockContainerManager_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockContainerManager_Expecter) ListVolumes(context1 interface{}) *MockContainerManager_ListVolumes_Call {
	return &MockContainerManager_ListVolumes_Call{Call: _e.mock.On("ListVolumes", context1)}
}

func (_c *MockContainerManager_ListVolumes_Call) Run(run func(context1 context.Context)) *MockContainerManager_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerManager_ListVolumes_Call) Return(volumes []*containers.Volume, err error) *MockContainerManager_ListVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockContainerManager_ListVolumes_Call) RunAndReturn(run func(context1 context.Context) ([]*containers.Volume, error)) *MockContainerManager_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) RemoveImage(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type MockContainerManager_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) RemoveImage(context1 interface{}, s interface{}) *MockContainerManager_RemoveImage_Call {
	return &MockContainerManager_RemoveImage_Call{Call: _e.mock.On("RemoveImage", context1, s)}
}

func (_c *MockContainerManager_RemoveImage_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_RemoveImage_Call) Return(err error) *MockContainerManager_RemoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_RemoveImage_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockContainerManager_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNetwork provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) RemoveNetwork(context1 context.Context, network *containers.Network) error {
	ret := _mock.Called(context1, network)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Network) error); ok {
		r0 = returnFunc(context1, network)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_RemoveNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNetwork'
type MockContainerManager_RemoveNetwork_Call struct {
	*mock.Call
}

// RemoveNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - network *containers.Network
func (_e *MockContainerManager_Expecter) RemoveNetwork(context1 interface{}, network interface{}) *MockContainerManager_RemoveNetwork_Call {
	return &MockContainerManager_RemoveNetwork_Call{Call: _e.mock.On("RemoveNetwork", context1, network)}
}

func (_c *MockContainerManager_RemoveNetwork_Call) Run(run func(context1 context.Context, network *containers.Network)) *MockContainerManager_RemoveNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Network
		if args[1] != nil {
			arg1 = args[1].(*containers.Network)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_RemoveNetwork_Call) Return(err error) *MockContainerManager_RemoveNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_RemoveNetwork_Call) RunAndReturn(run func(context1 context.Context, network *containers.Network) error) *MockContainerManager_RemoveNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSecret provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) RemoveSecret(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_RemoveSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSecret'
type MockContainerManager_RemoveSecret_Call struct {
	*mock.Call
}

// RemoveSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockContainerManager_Expecter) RemoveSecret(context1 interface{}, s interface{}) *MockContainerManager_RemoveSecret_Call {
	return &MockContainerManager_RemoveSecret_Call{Call: _e.mock.On("RemoveSecret", context1, s)}
}

func (_c *MockContainerManager_RemoveSecret_Call) Run(run func(context1 context.Context, s string)) *MockContainerManager_RemoveSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_RemoveSecret_Call) Return(err error) *MockContainerManager_RemoveSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_RemoveSecret_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockContainerManager_RemoveSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVolume provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) RemoveVolume(context1 context.Context, volume *containers.Volume) error {
	ret := _mock.Called(context1, volume)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *containers.Volume) error); ok {
		r0 = returnFunc(context1, volume)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_RemoveVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVolume'
type MockContainerManager_RemoveVolume_Call struct {
	*mock.Call
}

// RemoveVolume is a helper method to define mock.On call
//   - context1 context.Context
//   - volume *containers.Volume
func (_e *MockContainerManager_Expecter) RemoveVolume(context1 interface{}, volume interface{}) *MockContainerManager_RemoveVolume_Call {
	return &MockContainerManager_RemoveVolume_Call{Call: _e.mock.On("RemoveVolume", context1, volume)}
}

func (_c *MockContainerManager_RemoveVolume_Call) Run(run func(context1 context.Context, volume *containers.Volume)) *MockContainerManager_RemoveVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *containers.Volume
		if args[1] != nil {
			arg1 = args[1].(*containers.Volume)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerManager_RemoveVolume_Call) Return(err error) *MockContainerManager_RemoveVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_RemoveVolume_Call) RunAndReturn(run func(context1 context.Context, volume *containers.Volume) error) *MockContainerManager_RemoveVolume_Call {
	_c.Call.Return(run)
	return _c
}

// SecretName provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) SecretName(s string) string {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for SecretName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContainerManager_SecretName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretName'
type MockContainerManager_SecretName_Call struct {
	*mock.Call
}

// SecretName is a helper method to define mock.On call
//   - s string
func (_e *MockContainerManager_Expecter) SecretName(s interface{}) *MockContainerManager_SecretName_Call {
	return &MockContainerManager_SecretName_Call{Call: _e.mock.On("SecretName", s)}
}

func (_c *MockContainerManager_SecretName_Call) Run(run func(s string)) *MockContainerManager_SecretName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerManager_SecretName_Call) Return(s1 string) *MockContainerManager_SecretName_Call {
	_c.Call.Return(s1)
	return _c
}

func (_c *MockContainerManager_SecretName_Call) RunAndReturn(run func(s string) string) *MockContainerManager_SecretName_Call {
	_c.Call.Return(run)
	return _c
}

// WriteSecret provides a mock function for the type MockContainerManager
func (_mock *MockContainerManager) WriteSecret(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for WriteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerManager_WriteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSecret'
type MockContainerManager_WriteSecret_Call struct {
	*mock.Call
}

// WriteSecret is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockContainerManager_Expecter) WriteSecret(context1 interface{}, s interface{}, s1 interface{}) *MockContainerManager_WriteSecret_Call {
	return &MockContainerManager_WriteSecret_Call{Call: _e.mock.On("WriteSecret", context1, s, s1)}
}

func (_c *MockContainerManager_WriteSecret_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockContainerManager_WriteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainerManager_WriteSecret_Call) Return(err error) *MockContainerManager_WriteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerManager_WriteSecret_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *MockContainerManager_WriteSecret_Call {
	_c.Call.Return(run)
	return _c
}
