version = 1

[values]
Repo = "git@github.com:materia/materia_repo"
RemoteHost = "github.com"
AgeKeyLocation = "scripts/testrepo/test-key.txt"

[env]
MATERIA_DEBUG = "true"
MATERIA_DIFFS = "true"
MATERIA_SOURCE_URL = "{{ .Repo }}"
MATERIA_GIT_PRIVATE_KEY = ".ssh/materia_key"
MATERIA_HOSTNAME = "localhost"
REMOTEHOST = "{{ .RemoteHost }}"

[[steps]]
[steps.shell]
script = """
yum install -y make rsync podman git
mkdir -p /var/lib/materia
mkdir -p /etc/materia
"""

[[steps]]
[steps.rsync]
source = "bin/materia-amd64"
dest = "/usr/local/bin/materia"

[[steps]]
[steps.rsync]
source = "scripts/_vm/auth/*"
dest = "/root/.ssh/"

[[steps]]
[steps.rsync]
source = "{{ .AgeKeyLocation }}"
dest = "/etc/materia/key.txt"

[[steps]]
[steps.rsync]
source = "scripts/testrepo"
dest = "/tmp/testrepo/"

[[steps]]
[steps.rsync]
source = "scripts/_vm/out/"
dest = "/tmp/out/"

[[steps]]
[steps.shell]
script = """
ssh-keyscan $REMOTEHOST >> ~/.ssh/known_hosts
"""
