secrets = "age"
age.keyfile = "./test-key.txt"
age.basedir = "secrets"

[hosts.localhost]
components = ["freshrss"]
roles = ["base", "double"]

[roles.base]
components = ["carpal"]

[roles.double]
components = ["double"]
