components.hello.containerTag = "stable"
components.double.containerTag = "latest"
[services.goodbye]
resource = "goodbye.container"
[services.hello]
resource = "hello.timer"
dependencies = ["hello.container"]
