// Code generated by "stringer -type ServiceAction -trimprefix Service"; DO NOT EDIT.

package services

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceStart-0]
	_ = x[ServiceStop-1]
	_ = x[ServiceRestart-2]
	_ = x[ServiceReloadUnits-3]
	_ = x[ServiceEnable-4]
	_ = x[ServiceDisable-5]
	_ = x[ServiceReloadService-6]
}

const _ServiceAction_name = "StartStopRestartReloadUnitsEnableDisableReloadService"

var _ServiceAction_index = [...]uint8{0, 5, 9, 16, 27, 33, 40, 53}

func (i ServiceAction) String() string {
	if i < 0 || i >= ServiceAction(len(_ServiceAction_index)-1) {
		return "ServiceAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceAction_name[_ServiceAction_index[i]:_ServiceAction_index[i+1]]
}
