---
site_name: Materia Docs
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Cheatsheet: cheatsheet.md
  - Secrets: secrets.md
  - Reference: reference/index.md
theme:
  name: readthedocs
repo_url: https://github.com/stryan/materia/
edit_uri: docs/markdown/
docs_dir: markdown
exclude_docs: |
  athanor.1.md
not_in_nav: |-
  /reference/*.*.md
