secrets = "age"
age.idents = "./test-key.txt"
[hosts.localhost]
components = ["hello","freshrss"]
roles = ["base","double"]

[roles.base]
components = ["carpal"]

[roles.double]
components = ["double"]
