components.nothing.containerTag = "unstable"
components.hello.containerTag = "stable"
components.double.containerTag = "latest"
components.freshrss.timezone = "America/NewYork"
components.freshrss.cron = "1,31"
components.freshrss.domain = "rss.materia.com"
