components.nothing.containerTag = "unstable"
components.hello.containerTag = "stable"
components.double.containerTag = "latest"
components.freshrss.timezone = "America/NewYork"
components.freshrss.cron = "1,31"
components.freshrss.domain = "rss.materia.com"
[components.carpal]
ldapTemplate = """
  aliases:
    - "mailto:{{ index . "mail" }}"
  links:
    - rel: "http://openid.net/specs/connect/1.0/issuer"
      href: "https://login.foobar.com"
"""
configContents = """
driver: file
file:
  directory: /etc/carpal/resources/
"""
